In [92]:
import requests
import pandas as pd

#### Get Token: Client credentials
- Cannot Access Token Refresh
- Cannot Access User Resources

In [93]:
data = {
    'grant_type': 'client_credentials',
    'client_id': 'a75ddc29587045ac916c74e96dc22959',
    'client_secret': '1ccbd3309fc74ab9b55dd3ff6ac71958'
}

headers = {
    'Content-Type': 'application/x-www-form-urlencoded'
}

token_response = requests.post('https://accounts.spotify.com/api/token', data = data, headers = headers)

In [94]:
token_response_json = token_response.json()
token_type = token_response_json['token_type']
access_token = token_response_json['access_token']

headers = {
    'Authorization': token_type + '  ' + access_token
}

In [95]:
response = requests.get('https://api.spotify.com/v1/artists/4QvgGvpgzgyUOo8Yp8LDm9?si=YMs3IRAIQpq1uzhZOxlN8g', headers = headers)
response.json()
# popularity: The value will be between 0 and 100, with 100 being the most popular. The artist's popularity is calculated from the popularity of all the artist's tracks.

{'external_urls': {'spotify': 'https://open.spotify.com/artist/4QvgGvpgzgyUOo8Yp8LDm9'},
 'followers': {'href': None, 'total': 3770365},
 'genres': ['anime rock', 'j-pop', 'j-rock'],
 'href': 'https://api.spotify.com/v1/artists/4QvgGvpgzgyUOo8Yp8LDm9',
 'id': '4QvgGvpgzgyUOo8Yp8LDm9',
 'images': [{'height': 640,
   'url': 'https://i.scdn.co/image/ab6761610000e5eb968120b0312a7893ec391560',
   'width': 640},
  {'height': 320,
   'url': 'https://i.scdn.co/image/ab67616100005174968120b0312a7893ec391560',
   'width': 320},
  {'height': 160,
   'url': 'https://i.scdn.co/image/ab6761610000f178968120b0312a7893ec391560',
   'width': 160}],
 'name': 'Mrs. GREEN APPLE',
 'popularity': 74,
 'type': 'artist',
 'uri': 'spotify:artist:4QvgGvpgzgyUOo8Yp8LDm9'}

In [96]:
# SEARCH
response = requests.get('https://api.spotify.com/v1/search?q=apple&type=artist&market=JP&limit=20&offset=0&include_external=audio', headers = headers)
# 我的token會回傳跟我的帳號位置為優先的結果而非我指定的JP

pd.json_normalize(response.json()['artists']['items'])

,genres,href,id,images,name,popularity,type,uri,external_urls.spotify,followers.href,followers.total
0,"[denver indie, elephant 6, lo-fi]",https://api.spotify.com/v1/artists/5KIrQe9pb7t...,5KIrQe9pb7tn8y775PsoAP,"[{'height': 667, 'url': 'https://i.scdn.co/ima...",The Apples In Stereo,32,artist,spotify:artist:5KIrQe9pb7tn8y775PsoAP,https://open.spotify.com/artist/5KIrQe9pb7tn8y...,None,54598
1,"[anime rock, j-pop, j-rock]",https://api.spotify.com/v1/artists/4QvgGvpgzgy...,4QvgGvpgzgyUOo8Yp8LDm9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Mrs. GREEN APPLE,74,artist,spotify:artist:4QvgGvpgzgyUOo8Yp8LDm9,https://open.spotify.com/artist/4QvgGvpgzgyUOo...,None,3770365
2,"[emo, emo punk, lawrence ks indie, midwest emo]",https://api.spotify.com/v1/artists/0MkAzpDHUZp...,0MkAzpDHUZpuDnWGUII4RN,"[{'height': 750, 'url': 'https://i.scdn.co/ima...",The Appleseed Cast,26,artist,spotify:artist:0MkAzpDHUZpuDnWGUII4RN,https://open.spotify.com/artist/0MkAzpDHUZpuDn...,None,44782
3,"[organic ambient, space ambient]",https://api.spotify.com/v1/artists/2tXSmVWVgzU...,2tXSmVWVgzUAot6441wbTS,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Applefish,41,artist,spotify:artist:2tXSmVWVgzUAot6441wbTS,https://open.spotify.com/artist/2tXSmVWVgzUAot...,None,5211
4,"[art pop, chamber pop, dark pop, lilith, perma...",https://api.spotify.com/v1/artists/3g2kUQ6tHLL...,3g2kUQ6tHLLbmkV7T4GPtL,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Fiona Apple,61,artist,spotify:artist:3g2kUQ6tHLLbmkV7T4GPtL,https://open.spotify.com/artist/3g2kUQ6tHLLbmk...,None,1419483
5,[otacore],https://api.spotify.com/v1/artists/1r0v3fdCiqr...,1r0v3fdCiqrr9mYtvbCccT,[],Apple Jack,46,artist,spotify:artist:1r0v3fdCiqrr9mYtvbCccT,https://open.spotify.com/artist/1r0v3fdCiqrr9m...,None,9602
6,[],https://api.spotify.com/v1/artists/4Y2i9jhU3jW...,4Y2i9jhU3jW0PVsvTLIbWX,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Appleby,39,artist,spotify:artist:4Y2i9jhU3jW0PVsvTLIbWX,https://open.spotify.com/artist/4Y2i9jhU3jW0PV...,None,13606
7,[],https://api.spotify.com/v1/artists/5cvnoBNP942...,5cvnoBNP942Py3QEc8Gzc9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",apple-polisher,0,artist,spotify:artist:5cvnoBNP942Py3QEc8Gzc9,https://open.spotify.com/artist/5cvnoBNP942Py3...,None,305
8,[],https://api.spotify.com/v1/artists/68ax86IGwQY...,68ax86IGwQYZ8y45VdkryS,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Apple Thief,19,artist,spotify:artist:68ax86IGwQYZ8y45VdkryS,https://open.spotify.com/artist/68ax86IGwQYZ8y...,None,178
9,"[k-pop, k-pop girl group]",https://api.spotify.com/v1/artists/0qlWcS66ohO...,0qlWcS66ohOIi0M8JZwPft,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",GFRIEND,58,artist,spotify:artist:0qlWcS66ohOIi0M8JZwPft,https://open.spotify.com/artist/0qlWcS66ohOIi0...,None,1601241
10,[classic psychedelic rock],https://api.spotify.com/v1/artists/0LgBu2eNiNT...,0LgBu2eNiNTEaBlmw6Xh3C,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Apple,2,artist,spotify:artist:0LgBu2eNiNTEaBlmw6Xh3C,https://open.spotify.com/artist/0LgBu2eNiNTEaB...,None,369
11,[otacore],https://api.spotify.com/v1/artists/7ggsXdK95oJ...,7ggsXdK95oJBkuZu1txVjC,[],Applebloom,35,artist,spotify:artist:7ggsXdK95oJBkuZu1txVjC,https://open.spotify.com/artist/7ggsXdK95oJBku...,None,4231
12,[],https://api.spotify.com/v1/artists/0cLE7Rf26nP...,0cLE7Rf26nPEpDrm20OrHf,"[{'height': 1000, 'url': 'https://i.scdn.co/im...",Apple,10,artist,spotify:artist:0cLE7Rf26nPEpDrm20OrHf,https://open.spotify.com/artist/0cLE7Rf26nPEpD...,None,579
13,"[vocaloid, vocaloid rock]",https://api.spotify.com/v1/artists/3H5KqBHbMP9...,3H5KqBHbMP9yPjWvYC9weE,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",apple41,5,artist,spotify:artist:3H5KqBHbMP9yPjWvYC9weE,https://open.spotify.com/artist/3H5KqBHbMP9yPj...,None,1132
14,[],https://api.spotify.com/v1/artists/4m2REU3D38U...,4m2REU3D38UrcnW0b8Lr7X,[],Apple,0,artist,spotify:artist:4m2REU3D38UrcnW0b8Lr7X,https://open.spotify.com/artist/4m2REU3D38Urcn...,None,0
15,"[reggae, roots reggae, traditional reggae]",https://api.spotify.com/v1/artists/1R4VmYnD3iZ...,1R4VmYnD3iZlwBqgsPP5zm,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Apple Gabriel,31,artist,spotify:artist:1R4VmYnD3iZlwBqgsPP5zm,https://open.spotify.com/artist/1R4VmYnD3iZlwB...,None,11713
16,[],https://api.spotify.com/v1/artists/0DLvWQW4aC9...,0DLvWQW4aC9VNDJNjSybG6,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Apple,0,artist,spotify:artist:0DLvWQW4aC9VNDJNjSybG6,https://open.spotify.com/artist/0DLvWQW4aC9VND...,None,14
17,[chill-out trance],https://api.spotify.com/v1/artists/0bzZT5BwQ7R...,0bzZT5BwQ7RXTpQHKOAeG0,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Apple & Stone,30,artist,spotify:artist:0bzZT5BwQ7RXTpQHKOAeG0,https://open.spotify.com/artist/0bzZT5BwQ7RXTp...,None,2388
18,[],https://api.spotify.com/v1/artists/4eCchpHgzZS...,4eCchpHgzZSynRGSXWL2jZ,[],Apple,1,artist,spotify:artist:4eCchpHgzZSynRGSXWL2jZ,https://open.spotify.com/artist/4eCchpHgzZSynR...,None,60
19,[],https://api.spotify.com/v1/artists/7xPELX7MSjA...,7xPELX7MSjA7TwQceLy94I,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Apple Umunwa,16,artist,spotify:artist:7xPELX7MSjA7TwQceLy94I,https://open.spotify.com/artist/7xPELX7MSjA7Tw...,None,0

#### Get Token: Authorization code with PKCE
- CAN Access User Resources
- CAN Access Token Refresh

In [97]:
# MY SAVED TRACKS
response = requests.get('https://api.spotify.com/v1/me/tracks', headers = headers)

response.json()

{'error': {'status': 403, 'message': 'Forbidden.'}}

In [141]:
import requests
import base64
import hashlib
import secrets
from urllib.parse import urlencode

# 配置
client_id = 'a75ddc29587045ac916c74e96dc22959'
redirect_uri = 'http://localhost:8081'
authorization_endpoint = 'https://accounts.spotify.com/authorize'
token_endpoint = 'https://accounts.spotify.com/api/token'
scope = 'user-read-private user-read-email user-library-read user-follow-read user-read-recently-played'

# 生成 Code Verifier
code_verifier = ''.join(secrets.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789') for i in range(64))
code_verifier_bytes = code_verifier.encode()

# 計算 SHA-256 散列值
code_challenge = hashlib.sha256(code_verifier_bytes).digest()

# 將散列值進行 Base64 編碼
code_challenge_base64 = base64.urlsafe_b64encode(code_challenge).rstrip(b'=').decode()


# 構建授權 URL
auth_params = {
    'response_type': 'code',
    'client_id': client_id,
    'scope': scope,
    'code_challenge_method': 'S256',
    'code_challenge': code_challenge_base64,
    'redirect_uri': redirect_uri
}
auth_url = authorization_endpoint + '?' + urlencode(auth_params)

# 向 Spotify 授權服務器發送請求
print("請在瀏覽器中訪問以下 URL 以登錄並授權你的應用程序:")
print(auth_url)

# 解析返回的授權碼
authorization_code = input("請在重定向後的 URL 中提取授權碼: ")

# 用授權碼獲取訪問令牌
token_params = {
    'client_id': client_id,
    'grant_type': 'authorization_code',
    'code': authorization_code,
    'redirect_uri': redirect_uri,
    'code_verifier': code_verifier
}
response = requests.post(token_endpoint, data=token_params)
token_data = response.json()

# 保存和管理訪問令牌
access_token = token_data['access_token']
refresh_token = token_data['refresh_token']
expires_in = token_data['expires_in']

# 你可以根據需要保存 access_token 和 refresh_token，以便在以後的請求中使用它們
print("Access Token:", access_token)
print("Refresh Token:", refresh_token)
print("Expires in (seconds):", expires_in)

請在瀏覽器中訪問以下 URL 以登錄並授權你的應用程序:
https://accounts.spotify.com/authorize?response_type=code&client_id=a75ddc29587045ac916c74e96dc22959&scope=user-read-private+user-read-email+user-library-read+user-follow-read+user-read-recently-played&code_challenge_method=S256&code_challenge=ej4_mZ-g-csGxwhT7K2_5UFtU8tHks5C3W_SfVOoOXk&redirect_uri=http%3A%2F%2Flocalhost%3A8081
Access Token: BQAHcTn7KfeLsorjPAiw_1BzUrh2mleURQ1rJzGeeagahX1jIpx5NjrB4ILnxYEcQxOZNl6b0EpV8dVhxrewpZ1KCI0XpH3rFkZlM6sXT-LQms462XRE9iomvWUWhDkauHladnpPeyOs2uR-5_iMnfQtT6LujJjivOlUdvyP9J3DKltH7dhWHQeOBi9zUHzT92yM74jnRIk3n-DfYW8JI__AN2kPr9F7QbddSwx3
Refresh Token: AQCGR-SOG2LqTjJ_Q-ej1FDqbn2NrT-aR7DRfiaN6YRNETQXz0ssyeF45dEQ4OZHN0sD_Q6l_2QB6mx0B8SCbrAyn-D5QvjYX1AVS7kG3pHWQmzao1pNOd3vEaSiHelb_mg
Expires in (seconds): 3600

In [142]:
token_data

{'access_token': 'BQAHcTn7KfeLsorjPAiw_1BzUrh2mleURQ1rJzGeeagahX1jIpx5NjrB4ILnxYEcQxOZNl6b0EpV8dVhxrewpZ1KCI0XpH3rFkZlM6sXT-LQms462XRE9iomvWUWhDkauHladnpPeyOs2uR-5_iMnfQtT6LujJjivOlUdvyP9J3DKltH7dhWHQeOBi9zUHzT92yM74jnRIk3n-DfYW8JI__AN2kPr9F7QbddSwx3',
 'token_type': 'Bearer',
 'expires_in': 3600,
 'refresh_token': 'AQCGR-SOG2LqTjJ_Q-ej1FDqbn2NrT-aR7DRfiaN6YRNETQXz0ssyeF45dEQ4OZHN0sD_Q6l_2QB6mx0B8SCbrAyn-D5QvjYX1AVS7kG3pHWQmzao1pNOd3vEaSiHelb_mg',
 'scope': 'user-library-read user-follow-read user-read-email user-read-recently-played user-read-private'}

In [143]:
headers = {
    'Authorization': 'Bearer  ' + access_token
}

In [106]:
# MY SAVED TRACKS
# 要注意 Authorization scopes
response = requests.get('https://api.spotify.com/v1/me/tracks', headers = headers)

response.json()

{'href': 'https://api.spotify.com/v1/me/tracks?offset=0&limit=20',
 'items': [{'added_at': '2024-01-25T21:56:58Z',
   'track': {'album': {'album_type': 'album',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4QvgGvpgzgyUOo8Yp8LDm9'},
       'href': 'https://api.spotify.com/v1/artists/4QvgGvpgzgyUOo8Yp8LDm9',
       'id': '4QvgGvpgzgyUOo8Yp8LDm9',
       'name': 'Mrs. GREEN APPLE',
       'type': 'artist',
       'uri': 'spotify:artist:4QvgGvpgzgyUOo8Yp8LDm9'}],
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'external_urls': {'spotify': 'https://open.spotify.com/album/3j7aiYai9ezbvxVCgrd2mb'},
     'href': 'https://api.spotify.com/v1/albums/3j7aiYai9ezbvxVCgrd2mb',
     'id': '3j7aiYai9ezbvxVCgrd2mb',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273d482c602732da71e7cdf04c3',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02d482c602732da71e7cdf04c3',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851d482c602732da71e7cdf04c3',
       'width': 64}],
     'name': 'ANTENNA',
     'release_date': '2023-07-04',
     'release_date_precision': 'day',
     'total_tracks': 13,
     'type': 'album',
     'uri': 'spotify:album:3j7aiYai9ezbvxVCgrd2mb'},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4QvgGvpgzgyUOo8Yp8LDm9'},
      'href': 'https://api.spotify.com/v1/artists/4QvgGvpgzgyUOo8Yp8LDm9',
      'id': '4QvgGvpgzgyUOo8Yp8LDm9',
      'name': 'Mrs. GREEN APPLE',
      'type': 'artist',
      'uri': 'spotify:artist:4QvgGvpgzgyUOo8Yp8LDm9'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'disc_number': 1,
    'duration_ms': 272226,
    'explicit': False,
    'external_ids': {'isrc': 'JPPO02301108'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/0teqQ0PYqVDyyXJuPOyMhu'},
    'href': 'https://api.spotify.com/v1/tracks/0teqQ0PYqVDyyXJuPOyMhu',
    'id': '0teqQ0PYqVDyyXJuPOyMhu',
    'is_local': False,
    'name': 'ケセラセラ',
    'popularity': 75,
    'preview_url': 'https://p.scdn.co/mp3-preview/e478e76468edc516ba33118b000d22214b0e02e4?cid=a75ddc29587045ac916c74e96dc22959',
    'track_number': 5,
    'type': 'track',
    'uri': 'spotify:track:0teqQ0PYqVDyyXJuPOyMhu'}},
  {'added_at': '2024-01-09T02:10:28Z',
   'track': {'album': {'album_type': 'single',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0ebinq3ZTOQAJNag4sBTJj'},
       'href': 'https://api.spotify.com/v1/artists/0ebinq3ZTOQAJNag4sBTJj',
       'id': '0ebinq3ZTOQAJNag4sBTJj',
       'name': 'BiSH',
       'type': 'artist',
       'uri': 'spotify:artist:0ebinq3ZTOQAJNag4sBTJj'}],
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'PR',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'external_urls': {'spotify': 'https://open.spotify.com/album/1VoA8bMAIB5BRjSMqaFQkP'},
     'href': 'https://api.spotify.com/v1/albums/1VoA8bMAIB5BRjSMqaFQkP',
     'id': '1VoA8bMAIB5BRjSMqaFQkP',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b2734e98d18364fcb98e849e34f4',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e024e98d18364fcb98e849e34f4',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d000048514e98d18364fcb98e849e34f4',
       'width': 64}],
     'name': 'innocent arrogance',
     'release_date': '2023-04-02',
     'release_date_precision': 'day',
     'total_tracks': 1,
     'type': 'album',
     'uri': 'spotify:album:1VoA8bMAIB5BRjSMqaFQkP'},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0ebinq3ZTOQAJNag4sBTJj'},
      'href': 'https://api.spotify.com/v1/artists/0ebinq3ZTOQAJNag4sBTJj',
      'id': '0ebinq3ZTOQAJNag4sBTJj',
      'name': 'BiSH',
      'type': 'artist',
      'uri': 'spotify:artist:0ebinq3ZTOQAJNag4sBTJj'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'BY',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'PR',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'disc_number': 1,
    'duration_ms': 211911,
    'explicit': False,
    'external_ids': {'isrc': 'JPB602301342'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/7JgBlEV4AbeHVhaTczGdTg'},
    'href': 'https://api.spotify.com/v1/tracks/7JgBlEV4AbeHVhaTczGdTg',
    'id': '7JgBlEV4AbeHVhaTczGdTg',
    'is_local': False,
    'name': 'innocent arrogance',
    'popularity': 53,
    'preview_url': 'https://p.scdn.co/mp3-preview/6984bf8652230cad497e2beb72f0dcafde64b7d6?cid=a75ddc29587045ac916c74e96dc22959',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:7JgBlEV4AbeHVhaTczGdTg'}},
  {'added_at': '2023-10-02T00:08:15Z',
   'track': {'album': {'album_type': 'album',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4QvgGvpgzgyUOo8Yp8LDm9'},
       'href': 'https://api.spotify.com/v1/artists/4QvgGvpgzgyUOo8Yp8LDm9',
       'id': '4QvgGvpgzgyUOo8Yp8LDm9',
       'name': 'Mrs. GREEN APPLE',
       'type': 'artist',
       'uri': 'spotify:artist:4QvgGvpgzgyUOo8Yp8LDm9'}],
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'external_urls': {'spotify': 'https://open.spotify.com/album/3j7aiYai9ezbvxVCgrd2mb'},
     'href': 'https://api.spotify.com/v1/albums/3j7aiYai9ezbvxVCgrd2mb',
     'id': '3j7aiYai9ezbvxVCgrd2mb',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273d482c602732da71e7cdf04c3',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02d482c602732da71e7cdf04c3',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851d482c602732da71e7cdf04c3',
       'width': 64}],
     'name': 'ANTENNA',
     'release_date': '2023-07-04',
     'release_date_precision': 'day',
     'total_tracks': 13,
     'type': 'album',
     'uri': 'spotify:album:3j7aiYai9ezbvxVCgrd2mb'},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4QvgGvpgzgyUOo8Yp8LDm9'},
      'href': 'https://api.spotify.com/v1/artists/4QvgGvpgzgyUOo8Yp8LDm9',
      'id': '4QvgGvpgzgyUOo8Yp8LDm9',
      'name': 'Mrs. GREEN APPLE',
      'type': 'artist',
      'uri': 'spotify:artist:4QvgGvpgzgyUOo8Yp8LDm9'}],
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'disc_number': 1,
    'duration_ms': 263106,
    'explicit': False,
    'external_ids': {'isrc': 'JPPO02301883'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/170XOP1T4MvY9TLTgPw07D'},
    'href': 'https://api.spotify.com/v1/tracks/170XOP1T4MvY9TLTgPw07D',
    'id': '170XOP1T4MvY9TLTgPw07D',
    'is_local': False,
    'name': 'Magic',
    'popularity': 74,
    'preview_url': 'https://p.scdn.co/mp3-preview/35090d6cdba771ef125cf304aef19c7ae6929379?cid=a75ddc29587045ac916c74e96dc22959',
    'track_number': 2,
    'type': 'track',
    'uri': 'spotify:track:170XOP1T4MvY9TLTgPw07D'}},
  {'added_at': '2023-04-24T23:53:11Z',
   'track': {'album': {'album_type': 'single',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0bAsR2unSRpn6BQPEnNlZm'},
       'href': 'https://api.spotify.com/v1/artists/0bAsR2unSRpn6BQPEnNlZm',
       'id': '0bAsR2unSRpn6BQPEnNlZm',
       'name': 'Aimer',
       'type': 'artist',
       'uri': 'spotify:artist:0bAsR2unSRpn6BQPEnNlZm'}],
     'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',

In [102]:
pd.json_normalize(response.json()['items'])

,added_at,track.album.album_type,track.album.artists,track.album.available_markets,track.album.external_urls.spotify,track.album.href,track.album.id,track.album.images,track.album.name,track.album.release_date,...,track.external_urls.spotify,track.href,track.id,track.is_local,track.name,track.popularity,track.preview_url,track.track_number,track.type,track.uri
0,2024-01-25T21:56:58Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/3j7aiYai9ezbvxV...,https://api.spotify.com/v1/albums/3j7aiYai9ezb...,3j7aiYai9ezbvxVCgrd2mb,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",ANTENNA,2023-07-04,...,https://open.spotify.com/track/0teqQ0PYqVDyyXJ...,https://api.spotify.com/v1/tracks/0teqQ0PYqVDy...,0teqQ0PYqVDyyXJuPOyMhu,False,ケセラセラ,75,https://p.scdn.co/mp3-preview/e478e76468edc516...,5,track,spotify:track:0teqQ0PYqVDyyXJuPOyMhu
1,2024-01-09T02:10:28Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/1VoA8bMAIB5BRjS...,https://api.spotify.com/v1/albums/1VoA8bMAIB5B...,1VoA8bMAIB5BRjSMqaFQkP,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",innocent arrogance,2023-04-02,...,https://open.spotify.com/track/7JgBlEV4AbeHVha...,https://api.spotify.com/v1/tracks/7JgBlEV4AbeH...,7JgBlEV4AbeHVhaTczGdTg,False,innocent arrogance,53,https://p.scdn.co/mp3-preview/6984bf8652230cad...,1,track,spotify:track:7JgBlEV4AbeHVhaTczGdTg
2,2023-10-02T00:08:15Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/3j7aiYai9ezbvxV...,https://api.spotify.com/v1/albums/3j7aiYai9ezb...,3j7aiYai9ezbvxVCgrd2mb,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",ANTENNA,2023-07-04,...,https://open.spotify.com/track/170XOP1T4MvY9TL...,https://api.spotify.com/v1/tracks/170XOP1T4MvY...,170XOP1T4MvY9TLTgPw07D,False,Magic,74,https://p.scdn.co/mp3-preview/35090d6cdba771ef...,2,track,spotify:track:170XOP1T4MvY9TLTgPw07D
3,2023-04-24T23:53:11Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/1gfSftIuafqkGu2...,https://api.spotify.com/v1/albums/1gfSftIuafqk...,1gfSftIuafqkGu28ely5z6,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",残響散歌,2021-12-06,...,https://open.spotify.com/track/7v8wKvNQQIxkugC...,https://api.spotify.com/v1/tracks/7v8wKvNQQIxk...,7v8wKvNQQIxkugCFFjrkaO,False,残響散歌,69,https://p.scdn.co/mp3-preview/3061d9bf1be9150e...,1,track,spotify:track:7v8wKvNQQIxkugCFFjrkaO
4,2023-04-20T00:13:32Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/4aD2P4IT3O69rPM...,https://api.spotify.com/v1/albums/4aD2P4IT3O69...,4aD2P4IT3O69rPMMKDpb51,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",NAMELESS WORLD,2005-05-11,...,https://open.spotify.com/track/72hNepjvepk9pKE...,https://api.spotify.com/v1/tracks/72hNepjvepk9...,72hNepjvepk9pKEcnGOs2f,False,ここにしか咲かない花,51,https://p.scdn.co/mp3-preview/a90c872b83409b2d...,4,track,spotify:track:72hNepjvepk9pKEcnGOs2f
5,2023-04-20T00:13:02Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6CM8A3Uhws8mAcN...,https://api.spotify.com/v1/albums/6CM8A3Uhws8m...,6CM8A3Uhws8mAcNOxpBRNq,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Chou Ikimonobakari Tennen Kinen Members Best S...,2006,...,https://open.spotify.com/track/5CJy6pVmKBLXNTl...,https://api.spotify.com/v1/tracks/5CJy6pVmKBLX...,5CJy6pVmKBLXNTlzrmZCEV,False,YELL,37,https://p.scdn.co/mp3-preview/d331ba5cf12479da...,7,track,spotify:track:5CJy6pVmKBLXNTlzrmZCEV
6,2023-04-20T00:12:41Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6MX0ObRrXzZW22t...,https://api.spotify.com/v1/albums/6MX0ObRrXzZW...,6MX0ObRrXzZW22tUXsb81z,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",VOICE,2008-12-03,...,https://open.spotify.com/track/5qRiFTBYluZppQa...,https://api.spotify.com/v1/tracks/5qRiFTBYluZp...,5qRiFTBYluZppQaxp5bGmK,False,ORION,50,https://p.scdn.co/mp3-preview/09fa1b200113aa4a...,5,track,spotify:track:5qRiFTBYluZppQaxp5bGmK
7,2022-11-23T13:41:04Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/50huwvIDzahdMng...,https://api.spotify.com/v1/albums/50huwvIDzahd...,50huwvIDzahdMng8css6iW,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",One Song From Two Hearts,2013-12-18,...,https://open.spotify.com/track/37u9hz6KIJ3ThDY...,https://api.spotify.com/v1/tracks/37u9hz6KIJ3T...,37u9hz6KIJ3ThDYFTMzU5U,False,流星,50,https://p.scdn.co/mp3-preview/9915ef598f8e3a70...,11,track,spotify:track:37u9hz6KIJ3ThDYFTMzU5U
8,2022-11-23T12:48:24Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6kG2cUR1dGvardD...,https://api.spotify.com/v1/albums/6kG2cUR1dGva...,6kG2cUR1dGvardDnsY9Bpy,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",シンクロニシティ (Special Edition),2018-04-18,...,https://open.spotify.com/track/3cZwlMEtYsc2c3d...,https://api.spotify.com/v1/tracks/3cZwlMEtYsc2...,3cZwlMEtYsc2c3d6ABFyOz,False,シンクロニシティ,52,https://p.scdn.co/mp3-preview/72f996788a938f5c...,1,track,spotify:track:3cZwlMEtYsc2c3d6ABFyOz
9,2022-11-23T12:48:19Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6h44qcqKe5voOXm...,https://api.spotify.com/v1/albums/6h44qcqKe5vo...,6h44qcqKe5voOXmriZOGNZ,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",サヨナラの意味 (Special Edition),2016-11-02,...,https://open.spotify.com/track/0lU7b9JpuI9RMVq...,https://api.spotify.com/v1/tracks/0lU7b9JpuI9R...,0lU7b9JpuI9RMVqqcJc5kd,False,サヨナラの意味,50,https://p.scdn.co/mp3-preview/4e09fd930bb91ac8...,1,track,spotify:track:0lU7b9JpuI9RMVqqcJc5kd
10,2022-11-23T12:48:13Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6JRJ7rS8nlHA2ZN...,https://api.spotify.com/v1/albums/6JRJ7rS8nlHA...,6JRJ7rS8nlHA2ZNZgznlEE,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",帰り道は遠回りしたくなる (Special Edition),2018-11-07,...,https://open.spotify.com/track/4RWJxm0Vn83uE0T...,https://api.spotify.com/v1/tracks/4RWJxm0Vn83u...,4RWJxm0Vn83uE0TIhwnABv,False,帰り道は遠回りしたくなる,52,https://p.scdn.co/mp3-preview/afacce857b171134...,1,track,spotify:track:4RWJxm0Vn83uE0TIhwnABv
11,2022-11-17T12:30:27Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CL, CO, CR, CY, C...",https://open.spotify.com/album/4dERKKPWhbvX7zx...,https://api.spotify.com/v1/albums/4dERKKPWhbvX...,4dERKKPWhbvX7zxFTzNzNn,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",MAGIC,2019-03-27,...,https://open.spotify.com/track/0Xn30nT5EKFPsWv...,https://api.spotify.com/v1/tracks/0Xn30nT5EKFP...,0Xn30nT5EKFPsWvpiJ2Iav,False,オールドファッション,65,https://p.scdn.co/mp3-preview/b72f16959d3fa17b...,6,track,spotify:track:0Xn30nT5EKFPsWvpiJ2Iav
12,2022-11-17T12:30:24Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6gnt7LdFIjqUsIs...,https://api.spotify.com/v1/albums/6gnt7LdFIjqU...,6gnt7LdFIjqUsIszpOVIrX,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",アイラブユー,2022-10-24,...,https://open.spotify.com/track/4gbHag1jhjLTDcr...,https://api.spotify.com/v1/tracks/4gbHag1jhjLT...,4gbHag1jhjLTDcrbfpFnYQ,False,アイラブユー,56,https://p.scdn.co/mp3-preview/207d7d104dd078f0...,1,track,spotify:track:4gbHag1jhjLTDcrbfpFnYQ
13,2022-11-17T12:30:23Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/4Z7pjeWlxxT8EXX...,https://api.spotify.com/v1/albums/4Z7pjeWlxxT8...,4Z7pjeWlxxT8EXXlxW5i4y,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",水平線,2021-08-13,...,https://open.spotify.com/track/5m1i6hq7dmRlp3c...,https://api.spotify.com/v1/tracks/5m1i6hq7dmRl...,5m1i6hq7dmRlp3c1utE48L,False,水平線,63,https://p.scdn.co/mp3-preview/4629728c0a8f766d...,1,track,spotify:track:5m1i6hq7dmRlp3c1utE48L
14,2022-11-17T12:30:20Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/0qmE5lDI6Z8enOe...,https://api.spotify.com/v1/albums/0qmE5lDI6Z8e...,0qmE5lDI6Z8enOel9hzkS8,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",ベルベットの詩,2022-08-26,...,https://open.spotify.com/track/2N4lCwOeFRX7qrb...,https://api.spotify.com/v1/tracks/2N4lCwOeFRX7...,2N4lCwOeFRX7qrbMPRcZ7d,False,ベルベットの詩,53,https://p.scdn.co/mp3-preview/792dbb87853c221d...,1,track,spotify:track:2N4lCwOeFRX7qrbMPRcZ7d
15,2022-11-10T16:10:40Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/12cXi1i1cgTVe27...,https://api.spotify.com/v1/albums/12cXi1i1cgTV...,12cXi1i1cgTVe27Rb122kZ,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Assort,2022-05-16,...,https://open.spotify.com/track/1VHL1PIkhDwWbFc...,https://api.spotify.com/v1/tracks/1VHL1PIkhDwW...,1VHL1PIkhDwWbFc65xHwOr,False,愛とか恋とか,67,https://p.scdn.co/mp3-preview/fc41f2a2d425b204...,5,track,spotify:track:1VHL1PIkhDwWbFc65xHwOr
16,2022-11-07T23:23:27Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6CGKNcn63JbPWlj...,https://api.spotify.com/v1/albums/6CGKNcn63JbP...,6CGKNcn63JbPWljHtQi1L0,"[{'height': 640, 'url': 'https://i.scdn.co/ima...","如果可以 (電影""月老""主題曲)",2021-11-05,...,https://open.spotify.com/track/72OVnXDzugvrCU2...,https://api.spotify.com/v1/tracks/72OVnXDzugvr...,72OVnXDzugvrCU25lMi9au,False,"如果可以 - 電影""月老""主題曲",68,https://p.scdn.co/mp3-preview/5631ff4232420b00...,1,track,spotify:track:72OVnXDzugvrCU25lMi9au
17,2022-10-31T10:48:08Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/5N4WUOp0F0eUngA...,https://api.spotify.com/v1/albums/5N4WUOp0F0eU...,5N4WUOp0F0eUngAyPXJico,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",花の塔,2022-07-03,...,https://open.spotify.com/track/1yt4wO7dKCwsfjc...,https://api.spotify.com/v1/tracks/1yt4wO7dKCws...,1yt4wO7dKCwsfjch8SN9aU,False,花の塔,56,https://p.scdn.co/mp3-preview/58ac8a36a9be1588...,1,track,spotify:track:1yt4wO7dKCwsfjch8SN9aU
18,2022-09-25T04:08:35Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/2mi78WPBCsQtGV7...,https://api.spotify.com/v1/albums/2mi78WPBCsQt...,2mi78WPBCsQtGV7MCTa6HK,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",長成什麼樣子算愛情,2021-12-10,...,https://open.spotify.com/track/1J6M0Lw3Gyam7qL...,https://api.spotify.com/v1/tracks/1J6M0Lw3Gyam...,1J6M0Lw3Gyam7qL4ndlXbF,False,長成什麼樣子算愛情,53,https://p.scdn.co/mp3-preview/0ef68a62acf35c05...,1,track,spotify:track:1J6M0Lw3Gyam7qL4ndlXbF
19,2022-08-18T18:18:31Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/7fjE2Zl2tNBBidh...,https://api.spotify.com/v1/albums/7fjE2Zl2tNBB...,7fjE2Zl2tNBBidhNGlo7AS,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",VIVID VICE,2021-01-16,...,https://open.spotify.com/track/4R6yPy83vDEZtwJ...,https://api.spotify.com/v1/tracks/4R6yPy83vDEZ...,4R6yPy83vDEZtwJsBavUfo,False,VIVID VICE,59,https://p.scdn.co/mp3-preview/f2de1555f48ebfe8...,1,track,spotify:track:4R6yPy83vDEZtwJsBavUfo

In [112]:
# Get Followed Artists
# https://developer.spotify.com/documentation/web-api/reference/get-followed
response = requests.get('https://api.spotify.com/v1/me/following?type=artist', headers = headers)

pd.json_normalize(response.json()['artists']['items'])

,genres,href,id,images,name,popularity,type,uri,external_urls.spotify,followers.href,followers.total
0,[],https://api.spotify.com/v1/artists/04JmQVFjqn5...,04JmQVFjqn5XHLOTqtRqYQ,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",BULLET PINK,11,artist,spotify:artist:04JmQVFjqn5XHLOTqtRqYQ,https://open.spotify.com/artist/04JmQVFjqn5XHL...,None,3893
1,"[anime, anime rock, j-pop]",https://api.spotify.com/v1/artists/0PYPjvZaOa7...,0PYPjvZaOa7bsCq26JOX8d,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",VK Blanka,53,artist,spotify:artist:0PYPjvZaOa7bsCq26JOX8d,https://open.spotify.com/artist/0PYPjvZaOa7bsC...,None,277890
2,"[j-pop, j-rock]",https://api.spotify.com/v1/artists/0jWCX6zp4Rj...,0jWCX6zp4RjWrmZRxJ2uri,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Novelbright,59,artist,spotify:artist:0jWCX6zp4RjWrmZRxJ2uri,https://open.spotify.com/artist/0jWCX6zp4RjWrm...,None,580921
3,"[j-pop, j-rock]",https://api.spotify.com/v1/artists/0wRzWf3I4lU...,0wRzWf3I4lUl9hdFF5uL0m,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Sukima Switch,54,artist,spotify:artist:0wRzWf3I4lUl9hdFF5uL0m,https://open.spotify.com/artist/0wRzWf3I4lUl9h...,None,1144226
4,"[classic j-pop, j-pop, j-rock]",https://api.spotify.com/v1/artists/1qma7XhwZot...,1qma7XhwZotCAucL7NHVLY,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Mr.Children,61,artist,spotify:artist:1qma7XhwZotCAucL7NHVLY,https://open.spotify.com/artist/1qma7XhwZotCAu...,None,3286972
5,[j-pop],https://api.spotify.com/v1/artists/45ft4DyTCEJ...,45ft4DyTCEJfQwTBHXpdhM,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",milet,60,artist,spotify:artist:45ft4DyTCEJfQwTBHXpdhM,https://open.spotify.com/artist/45ft4DyTCEJfQw...,None,786351
6,[j-pop boy group],https://api.spotify.com/v1/artists/5HQAzIHOdem...,5HQAzIHOdemXR2DoevwhjT,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",KAT-TUN,29,artist,spotify:artist:5HQAzIHOdemXR2DoevwhjT,https://open.spotify.com/artist/5HQAzIHOdemXR2...,None,130571
7,"[anime, anime rock, j-pop]",https://api.spotify.com/v1/artists/5Vo1hnCRmCM...,5Vo1hnCRmCM6M4thZCInCj,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",OFFICIAL HIGE DANDISM,67,artist,spotify:artist:5Vo1hnCRmCM6M4thZCInCj,https://open.spotify.com/artist/5Vo1hnCRmCM6M4...,None,6455065
8,[j-pop],https://api.spotify.com/v1/artists/5sefnd4yMQN...,5sefnd4yMQNYe9fuLi2XYw,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Hilcrhyme,44,artist,spotify:artist:5sefnd4yMQNYe9fuLi2XYw,https://open.spotify.com/artist/5sefnd4yMQNYe9...,None,232461
9,"[j-pop, japanese singer-songwriter]",https://api.spotify.com/v1/artists/6le80R1opKn...,6le80R1opKnTlP4o3KvA2k,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Uru,59,artist,spotify:artist:6le80R1opKnTlP4o3KvA2k,https://open.spotify.com/artist/6le80R1opKnTlP...,None,917461
10,"[anime, classic j-pop, j-pop, japanese singer-...",https://api.spotify.com/v1/artists/7lbSsjYACZH...,7lbSsjYACZHn1MSDXPxNF2,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Hikaru Utada,67,artist,spotify:artist:7lbSsjYACZHn1MSDXPxNF2,https://open.spotify.com/artist/7lbSsjYACZHn1M...,None,3383323

In [116]:
def fetch_all_artists(headers):
    base_url = 'https://api.spotify.com/v1/me/following?type=artist'

    all_artists = []
    next_url = base_url

    while next_url:
        response = requests.get(next_url, headers = headers)
        data = response.json()

        artists_on_page = data['artists']['items']
        all_artists.extend(artists_on_page)

        next_url = data["artists"]["next"]

    return all_artists

all_artists_data = fetch_all_artists(headers)

print("Total number of artists:", len(all_artists_data))

Total number of artists: 11

In [118]:
pd.json_normalize(all_artists_data)

,genres,href,id,images,name,popularity,type,uri,external_urls.spotify,followers.href,followers.total
0,[],https://api.spotify.com/v1/artists/04JmQVFjqn5...,04JmQVFjqn5XHLOTqtRqYQ,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",BULLET PINK,11,artist,spotify:artist:04JmQVFjqn5XHLOTqtRqYQ,https://open.spotify.com/artist/04JmQVFjqn5XHL...,None,3893
1,"[anime, anime rock, j-pop]",https://api.spotify.com/v1/artists/0PYPjvZaOa7...,0PYPjvZaOa7bsCq26JOX8d,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",VK Blanka,53,artist,spotify:artist:0PYPjvZaOa7bsCq26JOX8d,https://open.spotify.com/artist/0PYPjvZaOa7bsC...,None,277890
2,"[j-pop, j-rock]",https://api.spotify.com/v1/artists/0jWCX6zp4Rj...,0jWCX6zp4RjWrmZRxJ2uri,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Novelbright,59,artist,spotify:artist:0jWCX6zp4RjWrmZRxJ2uri,https://open.spotify.com/artist/0jWCX6zp4RjWrm...,None,580921
3,"[j-pop, j-rock]",https://api.spotify.com/v1/artists/0wRzWf3I4lU...,0wRzWf3I4lUl9hdFF5uL0m,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Sukima Switch,54,artist,spotify:artist:0wRzWf3I4lUl9hdFF5uL0m,https://open.spotify.com/artist/0wRzWf3I4lUl9h...,None,1144226
4,"[classic j-pop, j-pop, j-rock]",https://api.spotify.com/v1/artists/1qma7XhwZot...,1qma7XhwZotCAucL7NHVLY,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Mr.Children,61,artist,spotify:artist:1qma7XhwZotCAucL7NHVLY,https://open.spotify.com/artist/1qma7XhwZotCAu...,None,3286972
5,[j-pop],https://api.spotify.com/v1/artists/45ft4DyTCEJ...,45ft4DyTCEJfQwTBHXpdhM,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",milet,60,artist,spotify:artist:45ft4DyTCEJfQwTBHXpdhM,https://open.spotify.com/artist/45ft4DyTCEJfQw...,None,786351
6,[j-pop boy group],https://api.spotify.com/v1/artists/5HQAzIHOdem...,5HQAzIHOdemXR2DoevwhjT,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",KAT-TUN,29,artist,spotify:artist:5HQAzIHOdemXR2DoevwhjT,https://open.spotify.com/artist/5HQAzIHOdemXR2...,None,130571
7,"[anime, anime rock, j-pop]",https://api.spotify.com/v1/artists/5Vo1hnCRmCM...,5Vo1hnCRmCM6M4thZCInCj,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",OFFICIAL HIGE DANDISM,67,artist,spotify:artist:5Vo1hnCRmCM6M4thZCInCj,https://open.spotify.com/artist/5Vo1hnCRmCM6M4...,None,6455065
8,[j-pop],https://api.spotify.com/v1/artists/5sefnd4yMQN...,5sefnd4yMQNYe9fuLi2XYw,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Hilcrhyme,44,artist,spotify:artist:5sefnd4yMQNYe9fuLi2XYw,https://open.spotify.com/artist/5sefnd4yMQNYe9...,None,232461
9,"[j-pop, japanese singer-songwriter]",https://api.spotify.com/v1/artists/6le80R1opKn...,6le80R1opKnTlP4o3KvA2k,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Uru,59,artist,spotify:artist:6le80R1opKnTlP4o3KvA2k,https://open.spotify.com/artist/6le80R1opKnTlP...,None,917461
10,"[anime, classic j-pop, j-pop, japanese singer-...",https://api.spotify.com/v1/artists/7lbSsjYACZH...,7lbSsjYACZHn1MSDXPxNF2,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Hikaru Utada,67,artist,spotify:artist:7lbSsjYACZHn1MSDXPxNF2,https://open.spotify.com/artist/7lbSsjYACZHn1M...,None,3383323

In [122]:
# Arist -> get albums

response = requests.get('https://api.spotify.com/v1/artists/0PYPjvZaOa7bsCq26JOX8d/albums', headers = headers)

pd.json_normalize(response.json()['items'])

,album_group,album_type,artists,available_markets,href,id,images,name,release_date,release_date_precision,total_tracks,type,uri,external_urls.spotify
0,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/4KIbOyp2w1B2...,4KIbOyp2w1B2X0S6vy88Ij,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",VK Blanka LIVE HOUSE TOUR 2023,2023-10-25,day,18,album,spotify:album:4KIbOyp2w1B2X0S6vy88Ij,https://open.spotify.com/album/4KIbOyp2w1B2X0S...
1,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/5cosSyZC5J75...,5cosSyZC5J75qZ666f9hFM,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",LIVE at SHIBUYA FATE TOUR 2147,2022-08-22,day,19,album,spotify:album:5cosSyZC5J75qZ666f9hFM,https://open.spotify.com/album/5cosSyZC5J75qZ6...
2,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/6q1FkwyDJcYQ...,6q1FkwyDJcYQImWnK6UMCF,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",BEST ALBUM SUPERVILLAIN,2022-03-21,day,36,album,spotify:album:6q1FkwyDJcYQImWnK6UMCF,https://open.spotify.com/album/6q1FkwyDJcYQImW...
3,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/2TLSG2US3Gn5...,2TLSG2US3Gn5KKstbM6ipZ,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",FATE,2021-09-01,day,12,album,spotify:album:2TLSG2US3Gn5KKstbM6ipZ,https://open.spotify.com/album/2TLSG2US3Gn5KKs...
4,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/7DDrVqzCsXJA...,7DDrVqzCsXJAdR2fQh9GZD,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Devil,2020-03-04,day,11,album,spotify:album:7DDrVqzCsXJAdR2fQh9GZD,https://open.spotify.com/album/7DDrVqzCsXJAdR2...
5,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/5WiacWoGjt3y...,5WiacWoGjt3yMoK8vtQ0tz,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",wizard,2018-11-21,day,12,album,spotify:album:5WiacWoGjt3yMoK8vtQ0tz,https://open.spotify.com/album/5WiacWoGjt3yMoK...
6,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/0guChGuEDcTG...,0guChGuEDcTGZln5bhyuN2,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",FEARLESS,2017-07-05,day,12,album,spotify:album:0guChGuEDcTGZln5bhyuN2,https://open.spotify.com/album/0guChGuEDcTGZln...
7,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/3RywiZPaCkEW...,3RywiZPaCkEWRWxX4aKUVS,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Slave of Love,2016-10-26,day,7,album,spotify:album:3RywiZPaCkEWRWxX4aKUVS,https://open.spotify.com/album/3RywiZPaCkEWRWx...
8,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/1TDkkBebZkIx...,1TDkkBebZkIxM7XOV6satw,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Good Luck,2015-08-05,day,7,album,spotify:album:1TDkkBebZkIxM7XOV6satw,https://open.spotify.com/album/1TDkkBebZkIxM7X...
9,album,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/48BNJ0CelfB9...,48BNJ0CelfB9yhIDScDhnb,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",ツベルクリン,2014-10-15,day,8,album,spotify:album:48BNJ0CelfB9yhIDScDhnb,https://open.spotify.com/album/48BNJ0CelfB9yhI...
10,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/4x4weVNRwq6L...,4x4weVNRwq6Lxc3KAYozJB,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Never Run,2024-05-05,day,1,album,spotify:album:4x4weVNRwq6Lxc3KAYozJB,https://open.spotify.com/album/4x4weVNRwq6Lxc3...
11,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/04MIBSttVqz8...,04MIBSttVqz8KMppZWvheC,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Worldfly,2023-10-25,day,6,album,spotify:album:04MIBSttVqz8KMppZWvheC,https://open.spotify.com/album/04MIBSttVqz8KMp...
12,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/0GTl9PHpXPLC...,0GTl9PHpXPLCJ50xra0AQs,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Snake,2023-08-30,day,1,album,spotify:album:0GTl9PHpXPLCJ50xra0AQs,https://open.spotify.com/album/0GTl9PHpXPLCJ50...
13,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/0S75gwZK3LNe...,0S75gwZK3LNeFQB8xqjllT,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",革命,2023-03-29,day,1,album,spotify:album:0S75gwZK3LNeFQB8xqjllT,https://open.spotify.com/album/0S75gwZK3LNeFQB...
14,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/0ykHMHtcrB2M...,0ykHMHtcrB2MJcoaibsye2,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",United,2022-08-22,day,4,album,spotify:album:0ykHMHtcrB2MJcoaibsye2,https://open.spotify.com/album/0ykHMHtcrB2MJco...
15,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/2xJ9ttPAKlrV...,2xJ9ttPAKlrV7k9X9JDXHO,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",This Kiss,2022-07-20,day,1,album,spotify:album:2xJ9ttPAKlrV7k9X9JDXHO,https://open.spotify.com/album/2xJ9ttPAKlrV7k9...
16,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/4XKcpxTLKwtG...,4XKcpxTLKwtGD2z9f8Vl9w,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Treasure,2022-06-03,day,1,album,spotify:album:4XKcpxTLKwtGD2z9f8Vl9w,https://open.spotify.com/album/4XKcpxTLKwtGD2z...
17,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/4GtfZHSWZipf...,4GtfZHSWZipfAu0i5XH3Pr,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Changes,2022-04-13,day,1,album,spotify:album:4GtfZHSWZipfAu0i5XH3Pr,https://open.spotify.com/album/4GtfZHSWZipfAu0...
18,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/4sp1Czs2EWRd...,4sp1Czs2EWRdvyeZRcKSvV,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",北斗七星,2021-10-22,day,2,album,spotify:album:4sp1Czs2EWRdvyeZRcKSvV,https://open.spotify.com/album/4sp1Czs2EWRdvye...
19,single,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://api.spotify.com/v1/albums/6Jq0UXdjPgzj...,6Jq0UXdjPgzjo4x71aVW1g,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",STRESS (Vicke Blanka Remix),2021-09-29,day,1,album,spotify:album:6Jq0UXdjPgzjo4x71aVW1g,https://open.spotify.com/album/6Jq0UXdjPgzjo4x...

In [128]:
# Album -> get tracks

response = requests.get('https://api.spotify.com/v1/albums/6q1FkwyDJcYQImWnK6UMCF/tracks', headers = headers)

pd.json_normalize(response.json()['items'])

,artists,disc_number,duration_ms,explicit,href,id,is_local,is_playable,name,preview_url,track_number,type,uri,external_urls.spotify
0,[{'external_urls': {'spotify': 'https://open.s...,1,252213,False,https://api.spotify.com/v1/tracks/7I8kMUSveBJ6...,7I8kMUSveBJ6WUbc4TcptQ,False,True,アイライキュー,https://p.scdn.co/mp3-preview/eeef7c722fbd8d5f...,1,track,spotify:track:7I8kMUSveBJ6WUbc4TcptQ,https://open.spotify.com/track/7I8kMUSveBJ6WUb...
1,[{'external_urls': {'spotify': 'https://open.s...,1,219986,False,https://api.spotify.com/v1/tracks/0bxDtb5ZNUd2...,0bxDtb5ZNUd2Eq5xH0t3nf,False,True,ウララ,https://p.scdn.co/mp3-preview/9748e99e40f97300...,2,track,spotify:track:0bxDtb5ZNUd2Eq5xH0t3nf,https://open.spotify.com/track/0bxDtb5ZNUd2Eq5...
2,[{'external_urls': {'spotify': 'https://open.s...,1,330000,False,https://api.spotify.com/v1/tracks/0sDWDasQSnRs...,0sDWDasQSnRsndkoEYg4ue,False,True,北斗七星,https://p.scdn.co/mp3-preview/d5242ca5e4854043...,3,track,spotify:track:0sDWDasQSnRsndkoEYg4ue,https://open.spotify.com/track/0sDWDasQSnRsndk...
3,[{'external_urls': {'spotify': 'https://open.s...,1,251986,False,https://api.spotify.com/v1/tracks/7mjamiJ2zplb...,7mjamiJ2zplbZQ2ymbn5T7,False,True,Winter Beat,https://p.scdn.co/mp3-preview/f60b4f0ba804729d...,4,track,spotify:track:7mjamiJ2zplbZQ2ymbn5T7,https://open.spotify.com/track/7mjamiJ2zplbZQ2...
4,[{'external_urls': {'spotify': 'https://open.s...,1,227826,False,https://api.spotify.com/v1/tracks/2ayROzS0w3bq...,2ayROzS0w3bqU80rpi5E8p,False,True,Slave of Love,https://p.scdn.co/mp3-preview/74ed221db90ffe40...,5,track,spotify:track:2ayROzS0w3bqU80rpi5E8p,https://open.spotify.com/track/2ayROzS0w3bqU80...
5,[{'external_urls': {'spotify': 'https://open.s...,1,248760,False,https://api.spotify.com/v1/tracks/7nijn5vW2tnV...,7nijn5vW2tnVhxlY8YCJW0,False,True,Ca Va?,https://p.scdn.co/mp3-preview/82916e3811e91f5b...,6,track,spotify:track:7nijn5vW2tnVhxlY8YCJW0,https://open.spotify.com/track/7nijn5vW2tnVhxl...
6,[{'external_urls': {'spotify': 'https://open.s...,1,224093,False,https://api.spotify.com/v1/tracks/1uaTul8wkNAp...,1uaTul8wkNApQfDXoWpRXv,False,True,白熊,https://p.scdn.co/mp3-preview/0edfb121be51541f...,7,track,spotify:track:1uaTul8wkNApQfDXoWpRXv,https://open.spotify.com/track/1uaTul8wkNApQfD...
7,[{'external_urls': {'spotify': 'https://open.s...,1,236973,False,https://api.spotify.com/v1/tracks/5EdOeT3HL4Tb...,5EdOeT3HL4TbmUF8fyDczy,False,True,まっしろ,https://p.scdn.co/mp3-preview/64011910dd980942...,8,track,spotify:track:5EdOeT3HL4TbmUF8fyDczy,https://open.spotify.com/track/5EdOeT3HL4TbmUF...
8,[{'external_urls': {'spotify': 'https://open.s...,1,249666,False,https://api.spotify.com/v1/tracks/2xsy2MtHv2Rl...,2xsy2MtHv2RljV7pUNOky1,False,True,WALK - long ver.,https://p.scdn.co/mp3-preview/3f0a362ba5fa2625...,9,track,spotify:track:2xsy2MtHv2RljV7pUNOky1,https://open.spotify.com/track/2xsy2MtHv2RljV7...
9,[{'external_urls': {'spotify': 'https://open.s...,1,291413,False,https://api.spotify.com/v1/tracks/0Kiw3CSJcUs2...,0Kiw3CSJcUs2y5XxYnccnU,False,True,ポニーテイル,https://p.scdn.co/mp3-preview/a431059a813e892d...,10,track,spotify:track:0Kiw3CSJcUs2y5XxYnccnU,https://open.spotify.com/track/0Kiw3CSJcUs2y5X...
10,[{'external_urls': {'spotify': 'https://open.s...,1,289000,False,https://api.spotify.com/v1/tracks/771tLAm7nhVL...,771tLAm7nhVLx3tn7lUKo2,False,True,ミラージュ,https://p.scdn.co/mp3-preview/e1f5d60f094e8e89...,11,track,spotify:track:771tLAm7nhVLx3tn7lUKo2,https://open.spotify.com/track/771tLAm7nhVLx3t...
11,[{'external_urls': {'spotify': 'https://open.s...,1,201160,False,https://api.spotify.com/v1/tracks/1oiYeBOXXQEr...,1oiYeBOXXQErNkv1nKneqc,False,True,Shekebon!,https://p.scdn.co/mp3-preview/94e7a46b250f1bec...,12,track,spotify:track:1oiYeBOXXQErNkv1nKneqc,https://open.spotify.com/track/1oiYeBOXXQErNkv...
12,[{'external_urls': {'spotify': 'https://open.s...,1,291280,False,https://api.spotify.com/v1/tracks/4zdguuSw5lf3...,4zdguuSw5lf3CP5H7H25TS,False,True,天,https://p.scdn.co/mp3-preview/2de3c9217f122420...,13,track,spotify:track:4zdguuSw5lf3CP5H7H25TS,https://open.spotify.com/track/4zdguuSw5lf3CP5...
13,[{'external_urls': {'spotify': 'https://open.s...,1,248413,False,https://api.spotify.com/v1/tracks/7N0Hk78K3DOo...,7N0Hk78K3DOosnkgmw0yn8,False,True,ココラムウ,https://p.scdn.co/mp3-preview/19ceef2e5ad670a5...,14,track,spotify:track:7N0Hk78K3DOosnkgmw0yn8,https://open.spotify.com/track/7N0Hk78K3DOosnk...
14,[{'external_urls': {'spotify': 'https://open.s...,1,299333,False,https://api.spotify.com/v1/tracks/78gokEpYyk4C...,78gokEpYyk4CyZhUm1XzVv,False,True,Echo,https://p.scdn.co/mp3-preview/6fd3fc7ee501c383...,15,track,spotify:track:78gokEpYyk4CyZhUm1XzVv,https://open.spotify.com/track/78gokEpYyk4CyZh...
15,[{'external_urls': {'spotify': 'https://open.s...,1,197746,False,https://api.spotify.com/v1/tracks/6nVa28hoKADN...,6nVa28hoKADNE9EHGAX2S0,False,True,蒼天のバンパイア,https://p.scdn.co/mp3-preview/ffb8ea8f6256b1d6...,16,track,spotify:track:6nVa28hoKADNE9EHGAX2S0,https://open.spotify.com/track/6nVa28hoKADNE9E...
16,[{'external_urls': {'spotify': 'https://open.s...,1,215440,False,https://api.spotify.com/v1/tracks/2FaSFL4NoIpX...,2FaSFL4NoIpXOiJbFQFfz1,False,True,キロン,https://p.scdn.co/mp3-preview/d2289685c8be58b4...,17,track,spotify:track:2FaSFL4NoIpXOiJbFQFfz1,https://open.spotify.com/track/2FaSFL4NoIpXOiJ...
17,[{'external_urls': {'spotify': 'https://open.s...,1,195280,False,https://api.spotify.com/v1/tracks/7gQEQ1f24Tek...,7gQEQ1f24TekDi9d2TRBBB,False,True,Natural Woman,https://p.scdn.co/mp3-preview/288a1e5dd10992b4...,18,track,spotify:track:7gQEQ1f24TekDi9d2TRBBB,https://open.spotify.com/track/7gQEQ1f24TekDi9...
18,[{'external_urls': {'spotify': 'https://open.s...,2,262746,False,https://api.spotify.com/v1/tracks/61sXTVb63Mg8...,61sXTVb63Mg8QfWa5sW63h,False,True,TARA - 2020 Mix,https://p.scdn.co/mp3-preview/96586e7a6a5804bf...,1,track,spotify:track:61sXTVb63Mg8QfWa5sW63h,https://open.spotify.com/track/61sXTVb63Mg8QfW...
19,[{'external_urls': {'spotify': 'https://open.s...,2,204106,False,https://api.spotify.com/v1/tracks/1dnRJU44Gty4...,1dnRJU44Gty4sCXDcygDPS,False,True,Stray Cat,https://p.scdn.co/mp3-preview/169ce17876aeb146...,2,track,spotify:track:1dnRJU44Gty4sCXDcygDPS,https://open.spotify.com/track/1dnRJU44Gty4sCX...

In [137]:
# Track -> Popularity(NOT actual streams): Get Several Tracks
# https://developer.spotify.com/documentation/web-api/reference/get-several-tracks


response = requests.get('https://api.spotify.com/v1/tracks?ids=7I8kMUSveBJ6WUbc4TcptQ,0bxDtb5ZNUd2Eq5xH0t3nf', headers = headers)

pd.json_normalize(response.json()['tracks'])

,artists,available_markets,disc_number,duration_ms,explicit,href,id,is_local,name,popularity,...,album.id,album.images,album.name,album.release_date,album.release_date_precision,album.total_tracks,album.type,album.uri,external_ids.isrc,external_urls.spotify
0,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,252213,False,https://api.spotify.com/v1/tracks/7I8kMUSveBJ6...,7I8kMUSveBJ6WUbc4TcptQ,False,アイライキュー,34,...,6q1FkwyDJcYQImWnK6UMCF,[{'url': 'https://i.scdn.co/image/ab67616d0000...,BEST ALBUM SUPERVILLAIN,2022-03-21,day,36,album,spotify:album:6q1FkwyDJcYQImWnK6UMCF,JPB602200937,https://open.spotify.com/track/7I8kMUSveBJ6WUb...
1,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",1,219986,False,https://api.spotify.com/v1/tracks/0bxDtb5ZNUd2...,0bxDtb5ZNUd2Eq5xH0t3nf,False,ウララ,22,...,6q1FkwyDJcYQImWnK6UMCF,[{'url': 'https://i.scdn.co/image/ab67616d0000...,BEST ALBUM SUPERVILLAIN,2022-03-21,day,36,album,spotify:album:6q1FkwyDJcYQImWnK6UMCF,JPB601800788,https://open.spotify.com/track/0bxDtb5ZNUd2Eq5...

In [140]:
# playlists -> tracks

response = requests.get('https://api.spotify.com/v1/playlists/37i9dQZEVXbKXQ4mDTEBXq', headers = headers)

pd.json_normalize(response.json()['tracks']['items']).columns

Index(['added_at', 'is_local', 'primary_color',
       'added_by.external_urls.spotify', 'added_by.href', 'added_by.id',
       'added_by.type', 'added_by.uri', 'track.preview_url',
       'track.available_markets', 'track.explicit', 'track.type',
       'track.episode', 'track.track', 'track.album.available_markets',
       'track.album.type', 'track.album.album_type', 'track.album.href',
       'track.album.id', 'track.album.images', 'track.album.name',
       'track.album.release_date', 'track.album.release_date_precision',
       'track.album.uri', 'track.album.artists',
       'track.album.external_urls.spotify', 'track.album.total_tracks',
       'track.artists', 'track.disc_number', 'track.track_number',
       'track.duration_ms', 'track.external_ids.isrc',
       'track.external_urls.spotify', 'track.href', 'track.id', 'track.name',
       'track.popularity', 'track.uri', 'track.is_local',
       'video_thumbnail.url'],
      dtype='object')

In [151]:
# Get Recently Played Tracks
# Authorization scopes: user-read-recently-played

# https://developer.spotify.com/documentation/web-api/reference/get-recently-played


response = requests.get('https://api.spotify.com/v1/me/player/recently-played', headers = headers)

#pd.json_normalize(response.json()['items'])

pd.json_normalize(response.json())

,items,next,limit,href,cursors.after,cursors.before
0,"[{'track': {'album': {'album_type': 'album', '...",https://api.spotify.com/v1/me/player/recently-...,20,https://api.spotify.com/v1/me/player/recently-...,1715700564948,1715688462229

In [154]:
# 上限只有50筆
#i = 0
base_url = 'https://api.spotify.com/v1/me/player/recently-played'

all_records = []
next_url = base_url

while next_url:# and i < 10:
    response = requests.get(next_url, headers = headers)
    data = response.json()

    records_on_page = data['items']
    all_records.extend(records_on_page)

    next_url = data['next']
    #i += 1


pd.json_normalize(all_records)

,played_at,track.album.album_type,track.album.artists,track.album.available_markets,track.album.external_urls.spotify,track.album.href,track.album.id,track.album.images,track.album.name,track.album.release_date,...,track.popularity,track.preview_url,track.track_number,track.type,track.uri,context.type,context.href,context.external_urls.spotify,context.uri,context
0,2024-05-14T15:32:46.901Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/46Ver97lrdYTBhx...,https://api.spotify.com/v1/albums/46Ver97lrdYT...,46Ver97lrdYTBhxMHqS1m0,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",産声,2020-10-23,...,44,https://p.scdn.co/mp3-preview/4fe0a38e43a92df6...,1,track,spotify:track:4Qu3gqkXT4gbuKBGlelM36,artist,https://api.spotify.com/v1/artists/63ylN6WBUUx...,https://open.spotify.com/artist/63ylN6WBUUxxMs...,spotify:artist:63ylN6WBUUxxMsySiDmr0B,NaN
1,2024-05-14T15:29:24.948Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/4TelhTcG92OqIhe...,https://api.spotify.com/v1/albums/4TelhTcG92Oq...,4TelhTcG92OqIhegkAFu9w,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Ammolite,2023-09-06,...,46,https://p.scdn.co/mp3-preview/3b834bb4d1f86766...,7,track,spotify:track:7sslhJXYXQFq4kqMEsJGVZ,artist,https://api.spotify.com/v1/artists/63ylN6WBUUx...,https://open.spotify.com/artist/63ylN6WBUUxxMs...,spotify:artist:63ylN6WBUUxxMsySiDmr0B,NaN
2,2024-05-14T15:24:38.232Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/4TelhTcG92OqIhe...,https://api.spotify.com/v1/albums/4TelhTcG92Oq...,4TelhTcG92OqIhegkAFu9w,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Ammolite,2023-09-06,...,47,https://p.scdn.co/mp3-preview/f343e3ae1b4e2471...,3,track,spotify:track:2cIptZ008X2ef7No6g54Px,artist,https://api.spotify.com/v1/artists/63ylN6WBUUx...,https://open.spotify.com/artist/63ylN6WBUUxxMs...,spotify:artist:63ylN6WBUUxxMsySiDmr0B,NaN
3,2024-05-14T15:20:55.447Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/4TelhTcG92OqIhe...,https://api.spotify.com/v1/albums/4TelhTcG92Oq...,4TelhTcG92OqIhegkAFu9w,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Ammolite,2023-09-06,...,44,https://p.scdn.co/mp3-preview/6e9836aecbdce667...,10,track,spotify:track:6Y8R8KtWiBxHfyXimlWPfC,artist,https://api.spotify.com/v1/artists/63ylN6WBUUx...,https://open.spotify.com/artist/63ylN6WBUUxxMs...,spotify:artist:63ylN6WBUUxxMsySiDmr0B,NaN
4,2024-05-14T15:16:33.766Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/4TelhTcG92OqIhe...,https://api.spotify.com/v1/albums/4TelhTcG92Oq...,4TelhTcG92OqIhegkAFu9w,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",Ammolite,2023-09-06,...,48,https://p.scdn.co/mp3-preview/73b2bd214d45f690...,2,track,spotify:track:7FUOFvIWDp4QNZTNU0HGgH,artist,https://api.spotify.com/v1/artists/63ylN6WBUUx...,https://open.spotify.com/artist/63ylN6WBUUxxMs...,spotify:artist:63ylN6WBUUxxMsySiDmr0B,NaN
5,2024-05-14T15:12:33.682Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/0PuGKOl8H5w8Ar0...,https://api.spotify.com/v1/albums/0PuGKOl8H5w8...,0PuGKOl8H5w8Ar0esB1f2V,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",蕾,2024-05-05,...,54,https://p.scdn.co/mp3-preview/aa2fbc4195808efe...,1,track,spotify:track:02J918WUY2J6jBLux5ONUI,artist,https://api.spotify.com/v1/artists/63ylN6WBUUx...,https://open.spotify.com/artist/63ylN6WBUUxxMs...,spotify:artist:63ylN6WBUUxxMsySiDmr0B,NaN
6,2024-05-14T15:09:21.132Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
7,2024-05-14T14:18:52.325Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
8,2024-05-14T14:14:14.285Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
9,2024-05-14T14:09:37.294Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
10,2024-05-14T14:04:59.278Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
11,2024-05-14T14:00:22.352Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
12,2024-05-14T13:55:45.332Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
13,2024-05-14T13:51:07.284Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
14,2024-05-14T13:46:30.284Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
15,2024-05-14T13:41:52.304Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
16,2024-05-14T13:37:15.355Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
17,2024-05-14T13:32:37.257Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
18,2024-05-14T13:28:00.273Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
19,2024-05-14T13:23:22.664Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
20,2024-05-14T12:07:42.229Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/4O53dhmIctih3p2...,https://api.spotify.com/v1/albums/4O53dhmIctih...,4O53dhmIctih3p2suAAgga,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",晴る,2024-01-05,...,78,https://p.scdn.co/mp3-preview/f7d89b3a4516027d...,1,track,spotify:track:5eY7692tmgHB9dbmq6wa2M,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
21,2024-05-14T12:02:53.226Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
22,2024-05-14T11:31:12.209Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/0AJ47lb4B3HBCrH...,https://api.spotify.com/v1/albums/0AJ47lb4B3HB...,0AJ47lb4B3HBCrHywk1efs,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",地獄恋文,2024-04-16,...,72,https://p.scdn.co/mp3-preview/fbea6aa320e659a2...,1,track,spotify:track:7eUt3Ed2PSocfPSVaNhAEI,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
23,2024-05-14T11:31:03.024Z,album,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/3j7aiYai9ezbvxV...,https://api.spotify.com/v1/albums/3j7aiYai9ezb...,3j7aiYai9ezbvxVCgrd2mb,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",ANTENNA,2023-07-04,...,75,https://p.scdn.co/mp3-preview/e478e76468edc516...,5,track,spotify:track:0teqQ0PYqVDyyXJuPOyMhu,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
24,2024-05-14T11:26:15.414Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
25,2024-05-14T11:19:34.082Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
26,2024-05-14T11:14:19.470Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
27,2024-05-14T11:09:42.018Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
28,2024-05-14T10:56:12.219Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
29,2024-05-14T10:51:34.818Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
30,2024-05-14T10:46:57.327Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
31,2024-05-14T10:42:19.930Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN
32,2024-05-14T10:37:42.477Z,single,[{'external_urls': {'spotify': 'https://open.s...,"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",https://open.spotify.com/album/6lVM8WvZY6lpBO9...,https://api.spotify.com/v1/albums/6lVM8WvZY6lp...,6lVM8WvZY6lpBO9zrBRnE9,"[{'height': 640, 'url': 'https://i.scdn.co/ima...",幾億光年,2024-01-24,...,79,https://p.scdn.co/mp3-preview/ea07c98661813cc0...,1,track,spotify:track:4dmruTsdHIOjfOIeaFitXK,playlist,https://api.spotify.com/v1/playlists/37i9dQZEV...,https://open.spotify.com/playlist/37i9dQZEVXbK...,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,NaN