In [39]:
import pandas as pd
from datetime import datetime, timezone
import numpy as np

#### Get Token: Authorization code with PKCE
- CAN Access User Resources
- CAN Access Token Refresh

In [19]:
'''
import requests
import base64
import hashlib
import secrets
from urllib.parse import urlencode

# 配置
client_id = 'a75ddc29587045ac916c74e96dc22959'
redirect_uri = 'http://localhost:8081'
authorization_endpoint = 'https://accounts.spotify.com/authorize'
token_endpoint = 'https://accounts.spotify.com/api/token'
scopes = ['user-read-private', 'user-read-email', 'user-library-read', 'user-follow-read', 'user-read-recently-played']
scope = ' '.join(scopes)

# 生成 Code Verifier
code_verifier = ''.join(secrets.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789') for i in range(64))
code_verifier_bytes = code_verifier.encode()

# 計算 SHA-256 散列值
code_challenge = hashlib.sha256(code_verifier_bytes).digest()

# 將散列值進行 Base64 編碼
code_challenge_base64 = base64.urlsafe_b64encode(code_challenge).rstrip(b'=').decode()


# 構建授權 URL
auth_params = {
    'response_type': 'code',
    'client_id': client_id,
    'scope': scope,
    'code_challenge_method': 'S256',
    'code_challenge': code_challenge_base64,
    'redirect_uri': redirect_uri
}
auth_url = authorization_endpoint + '?' + urlencode(auth_params)

# 向 Spotify 授權服務器發送請求
print("請在瀏覽器中訪問以下 URL 以登錄並授權你的應用程序:")
print(auth_url)

# 解析返回的授權碼
authorization_code = input("請在重定向後的 URL 中提取授權碼: ")

# 用授權碼獲取訪問令牌
token_params = {
    'client_id': client_id,
    'grant_type': 'authorization_code',
    'code': authorization_code,
    'redirect_uri': redirect_uri,
    'code_verifier': code_verifier
}
response = requests.post(token_endpoint, data=token_params)
token_data = response.json()

# 保存和管理訪問令牌
access_token = token_data['access_token']
refresh_token = token_data['refresh_token']
expires_in = token_data['expires_in']

# 你可以根據需要保存 access_token 和 refresh_token，以便在以後的請求中使用它們
print("Access Token:", access_token)
print("Refresh Token:", refresh_token)
print("Expires in (seconds):", expires_in)
'''

請在瀏覽器中訪問以下 URL 以登錄並授權你的應用程序:
https://accounts.spotify.com/authorize?response_type=code&client_id=a75ddc29587045ac916c74e96dc22959&scope=user-read-private+user-read-email+user-library-read+user-follow-read+user-read-recently-played&code_challenge_method=S256&code_challenge=i_x5hdL7TwY8TkHchKN7G8Xqkj5Do7AwNDXNsnm2bl0&redirect_uri=http%3A%2F%2Flocalhost%3A8081
Access Token: BQDLsQ5SLOBWszgUupssQDCFMD6d5VsaOw5HOo3LGW08x5DmfUh-ryO0-MNgTSLiDy4-Ov8uiVUa4PzkhqL-49XHWvjhaqdb-W1spXJ3FbOh1zbSqpe6BEZ-V-b-ICe8kYtT4UT-uKtRTxL444cnZ6LIV25cTiBXUd9xcBEADNBkfUw9-9ILWX8j8vHsLm0xyzmTtrysaCAJ19Dp_VdElK4KPwmIOfQ2Uhjxi-nV
Refresh Token: AQA8vophVnEFqsCpT33hUB0Q2lZ-Yv4t9k2uWI-xGehTBRYhsRbLKpbQICPdkRJ1R4mQFFtY9roK--Y-Ye3ltBmFa4no6V8ej1h4E1fEe6-rEMaDJX-ga4h0aFzscLjEd8I
Expires in (seconds): 3600

In [40]:
import requests
import json

def refresh_access_token():
    token_file_path = 'tokens.json'
    if os.path.exists(token_file_path):
        with open(token_file_path, 'r') as token_file:
            exist_token_data = json.load(token_file)

    # 配置
    client_id = 'a75ddc29587045ac916c74e96dc22959'
    client_secret = '1ccbd3309fc74ab9b55dd3ff6ac71958'
    refresh_token = exist_token_data['refresh_token']
    token_endpoint = 'https://accounts.spotify.com/api/token'

    token_params = {
        'grant_type': 'refresh_token', 
        'refresh_token': refresh_token, 
        'client_id': client_id, 
        'client_secret': client_secret 
    }
    response = requests.post(token_endpoint, data = token_params)
    token_data = response.json()

    # 更新和保存新的访问令牌
    access_token = token_data['access_token']
    if 'refresh_token' in token_data:
        refresh_token = token_data['refresh_token']
        
    print("Access Token:", access_token)
    print("Refresh Token:", refresh_token)
    print("Expires in (seconds):", token_data['expires_in'])

    with open('tokens.json', 'w') as token_file:
        json.dump(token_data, token_file)

refresh_access_token()

Access Token: BQC6OGgEq5jfflXkwyJ-XN4ETyK4A4C1UpQT5JhiT2ME9HMjrMM9uAU5-dUTnTE2JB2UnjoD--WYVkvqfA79WCTUD99voE2mIKLh-GAehvlLBB85bfnYkU6RehujK67XHQj726fuVCL6HFqf6nsIXmsjrUo-RwGAox1q8CNKtjgDgAU9R4DwEIO6Pq6kA7YUn0pKjVYBM_nGXBY5P6XhoM7MwIu33AzdYOF3yNkY
Refresh Token: AQDEyepNoggpsmjtDuzWyZ2C5PGprEgsdN6KcE23GBfPTneUDzA31uCK3veiCFYVdgeW34UOKO1WlQUOaN_v9KJWGn3qj43WRaD1omODTPxJpap8oF3yqsqJjCYcXW93TvaGhw
Expires in (seconds): 3600

In [41]:
token_file_path = 'tokens.json'
if os.path.exists(token_file_path):
    with open(token_file_path, 'r') as token_file:
        exist_token_data = json.load(token_file)

access_token = exist_token_data['access_token']

In [42]:
headers = {
    'Authorization': 'Bearer  ' + access_token
}

##### Predefine function

In [43]:
# by playlist -> get tracks

def playlist_get_tracks(playlist_id = 'me'):
    if playlist_id == 'me':
        # return my saved tracks
        base_url = 'https://api.spotify.com/v1/me/tracks'
    else:
        base_url = 'https://api.spotify.com/v1/playlists/' + playlist_id + '/tracks'
    
    # get json data
    next_url = base_url
    playlist_get_tracks_json = []
    while next_url:
        response = requests.get(next_url, headers = headers)
        data = response.json()
        # current items
        curr_page = data.get('items')
        playlist_get_tracks_json.extend(curr_page)
        # next page if exist
        next_url = data.get('next')
    
    # playlist_get_tracks, album_info
    playlist_get_tracks_list = []
    album_info_list = []
    if isinstance(playlist_get_tracks_json, list): 
        rank = 1
        for item in playlist_get_tracks_json:
            track_album = item.get('track').get('album')
            track = item.get('track')
            try:
                added_at_p = datetime.fromisoformat(item.get('added_at')[:-1]).replace(tzinfo = timezone.utc)
            except:
                added_at_p = np.nan
            try:
                track_album_release_date = datetime.strptime(track_album.get('release_date'), '%Y-%m-%d')
            except:
                track_album_release_date = np.nan
            
            playlist_get_tracks_data = {
                'sync_date': datetime.now(timezone.utc).replace(microsecond = 0), 
                'added_at': added_at_p, 
                'rank': rank, 
                'track_id': track.get('id'), 
                'album_id': track_album.get('id'), 
            }

            album_info_data = {
                'sync_date': datetime.now(timezone.utc).replace(microsecond = 0), 
                'album_id': track_album.get('id'), 
                'album_name': track_album.get('name'), 
                'album_release_date': track_album_release_date,  
                #'album_release_date_precision': track_album.get('release_date_precision'), 
            }

            playlist_get_tracks_list.append(playlist_get_tracks_data)
            album_info_list.append(album_info_data)
            rank += 1

    playlist_get_tracks_table = pd.DataFrame(playlist_get_tracks_list)
    album_info_table = pd.DataFrame(album_info_list)

    # track_artists
    track_artists_list = []
    if isinstance(playlist_get_tracks_json, list): 
        for item in playlist_get_tracks_json:
            track = item.get('track')
            # id
            track_id = track.get('id')

            if isinstance(track.get('artists'), list): 
                for artist in track.get('artists'):
                    # artist.id
                    track_artists_id = artist.get('id')
                    track_data = {
                        'sync_date': datetime.now(timezone.utc).replace(microsecond = 0),  
                        'track_id': track_id, 
                        'artist_id': track_artists_id, 
                    }
                    track_artists_list.append(track_data)

    track_artists_table = pd.DataFrame(track_artists_list)

    return playlist_get_tracks_table, album_info_table, track_artists_table

In [44]:
# get followed artists  
def get_following_artist():
    base_url = 'https://api.spotify.com/v1/me/following?type=artist'
    next_url = base_url

    following_atrists_json = []
    while next_url:
        response = requests.get(next_url, headers = headers)
        data = response.json()

        curr_page = data.get('artists', {}).get('items')
        following_atrists_json.extend(curr_page)

        next_url = data.get('artists', {}).get('next')
    
    following_atrists_list = []
    if isinstance(following_atrists_json, list): 
        for artist in following_atrists_json:
            following_atrists_data = {
                'sync_date': datetime.now(timezone.utc).replace(microsecond = 0), 
                'artist_id': artist.get('id'), 
                'artist_name': artist.get('name'), 
                'artist_popularity': int(artist.get('popularity')), 
                #'artist_type': artist.get('type'), 
                'artist_followers_total': int(artist.get('followers').get('total')), 
            }
            following_atrists_list.append(following_atrists_data)

    following_atrists_table = pd.DataFrame(following_atrists_list)
    return following_atrists_table

In [45]:
# by artist -> get albums
def artist_get_albums(artist_id):
    base_url = 'https://api.spotify.com/v1/artists/' + artist_id + '/albums'
    next_url = base_url

    atrist_albums_json = []
    while next_url:
        response = requests.get(next_url, headers = headers)
        data = response.json()

        curr_page = data.get('items')
        atrist_albums_json.extend(curr_page)

        next_url = data.get('next')
    
    atrist_albums_list = []
    if isinstance(atrist_albums_json, list): 
        for album in atrist_albums_json:
            try:
                album_release_date = datetime.strptime(album.get('release_date'), '%Y-%m-%d')
            except:
                album_release_date = np.nan
            atrist_albums_data = {
                'sync_date': datetime.now(timezone.utc).replace(microsecond = 0), 
                'album_id': album.get('id'), 
                'album_name': album.get('name'), 
                'album_release_date': album_release_date, 
                #'album_release_date_precision': album.get('release_date_precision'), 
            }
            atrist_albums_list.append(atrist_albums_data)

    atrist_albums_table = pd.DataFrame(atrist_albums_list)
    return atrist_albums_table

In [ ]:
'''
album_info_list = []
if isinstance(atrists_albums_json, list): 
    for albums in atrists_albums_json:
        albums_id = albums.get('id')

        if isinstance(albums.get('artists'), list): 
            for atrists in albums.get('artists'):
                albums_artists_id = artist.get('id')
            
                album_info_data = {
                    'albums.artist.id': albums_artists_id, 
                    'albums.id': albums_id, 
                }
                album_info_list.append(album_info_data)

album_info_table = pd.DataFrame(album_info_list)
'''

In [46]:
# by album -> get tracks
def album_get_tracks(album_id, artist_id):
    base_url = 'https://api.spotify.com/v1/albums/' + album_id + '/tracks'
    next_url = base_url

    album_tracks_json = []
    while next_url:
        response = requests.get(next_url, headers = headers)
        data = response.json()

        curr_page = data.get('items')
        if curr_page:
            album_tracks_json.extend(curr_page)

        next_url = data.get('next')
    
    # album_tracks, track_artists
    album_tracks_list = []
    track_artists_list = []
    if isinstance(album_tracks_json, list): 
        for track in album_tracks_json:
            # only include tracks of the target artist
            artists = track.get('artists', {})
            artists_list = [artist.get('id') for artist in artists]
            track_id = track.get('id')
            if artist_id in artists_list:
                album_tracks_data = {
                    'sync_date': datetime.now(timezone.utc).replace(microsecond = 0), 
                    'track_id': track_id, 
                    'album_id': album_id, 
                }
                album_tracks_list.append(album_tracks_data)
                
                for artist in artists:
                    # artist.id
                    track_artists_id = artist.get('id')
                    track_data = {
                        'sync_date': datetime.now(timezone.utc).replace(microsecond = 0),  
                        'track_id': track_id, 
                        'artist_id': track_artists_id, 
                    }
                    track_artists_list.append(track_data)

    album_tracks_table = pd.DataFrame(album_tracks_list)
    track_artists_table = pd.DataFrame(track_artists_list)
    
    return album_tracks_table, track_artists_table

In [47]:
# get track info

def get_track_info(track_list, max_idn = 100):
    track_info_list = []
    for i in range(len(track_list)//max_idn + 1):
        sub_track_list = track_list[i*max_idn: i*max_idn+max_idn]
        base_url = 'https://api.spotify.com/v1/tracks?ids=' + ','.join(sub_track_list)
        response = requests.get(base_url, headers = headers)
        data = response.json()
        track_info_json = data.get('tracks')

        if isinstance(track_info_json, list): 
            for track in track_info_json:
                track_info_data = {
                    'sync_date': datetime.now(timezone.utc).replace(microsecond = 0), 
                    'duration_ms': int(track.get('duration_ms')), 
                    'id': track.get('id'), 
                    'name': track.get('name'), 
                    'popularity': int(track.get('popularity')), 
                }
                track_info_list.append(track_info_data)

    track_info_table = pd.DataFrame(track_info_list)
    return track_info_table

In [48]:
# my_recently_played
def my_recently_played():
    base_url = 'https://api.spotify.com/v1/me/player/recently-played'
    # get json data
    all_records = []
    next_url = base_url
    while next_url:
        response = requests.get(next_url, headers = headers)
        data = response.json()
        records_on_page = data.get('items', {})
        all_records.extend(records_on_page)
        next_url = data.get('next')
    
    # all_records, album_info
    all_records_list = []
    album_info_list = []
    if isinstance(all_records, list): 
        rank = 1
        for item in all_records:
            track_album = item.get('track').get('album')
            track = item.get('track')
            try:
                played_at_p = datetime.fromisoformat(item.get('played_at')[:-1]).replace(tzinfo = timezone.utc)
            except:
                played_at_p = np.nan
            try:
                track_album_release_date = datetime.strptime(track_album.get('release_date'), '%Y-%m-%d')
            except:
                track_album_release_date = np.nan
            
            all_records_data = {
                'sync_date': datetime.now(timezone.utc).replace(microsecond = 0), 
                'played_at': played_at_p, 
                'rank': rank, 
                'track_id': track.get('id'), 
                'album_id': track_album.get('id'), 
            }

            album_info_data = {
                'sync_date': datetime.now(timezone.utc).replace(microsecond = 0), 
                'album_id': track_album.get('id'), 
                'album_name': track_album.get('name'), 
                'album_release_date': track_album_release_date,  
                #'album_release_date_precision': track_album.get('release_date_precision'), 
            }

            all_records_list.append(all_records_data)
            album_info_list.append(album_info_data)
            rank += 1

    all_records_table = pd.DataFrame(all_records_list)
    album_info_table = pd.DataFrame(album_info_list)

    # track_artists
    track_artists_list = []
    if isinstance(all_records, list): 
        for item in all_records:
            track = item.get('track')
            # id
            track_id = track.get('id')

            if isinstance(track.get('artists'), list): 
                for artist in track.get('artists'):
                    # artist.id
                    track_artists_id = artist.get('id')
                    track_data = {
                        'sync_date': datetime.now(timezone.utc).replace(microsecond = 0),  
                        'track_id': track_id, 
                        'artist_id': track_artists_id, 
                    }
                    track_artists_list.append(track_data)

    track_artists_table = pd.DataFrame(track_artists_list)

    return all_records_table, album_info_table, track_artists_table

In [49]:
# get more track feature
def get_track_feature(track_list, max_idn = 100):
    track_feature_list = []
    for i in range(len(track_list)//max_idn + 1):
        sub_track_list = track_list[i*max_idn: i*max_idn+max_idn]
        base_url = 'https://api.spotify.com/v1/audio-features?ids=' + ','.join(sub_track_list)
        response = requests.get(base_url, headers = headers)
        data = response.json()
        track_feature_json = data.get('audio_features')

        if isinstance(track_feature_json, list): 
            for track in track_feature_json:
                track_feature_data = {
                    'sync_date': datetime.now(timezone.utc).replace(microsecond = 0), 
                    'id': track.get('id'), 
                    'danceability': float(track.get('danceability')), 
                    'energy': float(track.get('energy')), 
                    'key': int(track.get('key')), 
                    'loudness': float(track.get('loudness')), 
                    'mode': int(track.get('mode')), 
                    'speechiness': float(track.get('speechiness')), 
                    'acousticness': float(track.get('acousticness')), 
                    'instrumentalness': float(track.get('instrumentalness')), 
                    'liveness': float(track.get('liveness')), 
                    'valence': float(track.get('valence')), 
                    'tempo': float(track.get('tempo')), 
                    'type': track.get('type'), 
                    'time_signature': int(track.get('time_signature')), 
                }
                track_feature_list.append(track_feature_data)

    track_feature_table = pd.DataFrame(track_feature_list)
    return track_feature_table

#### JP Top 50

In [11]:
playlist_id_jptop50 = '37i9dQZEVXbKXQ4mDTEBXq'
jptop50_table, jptop50_album_info, jptop50_track_artists_table = playlist_get_tracks(playlist_id_jptop50)

In [12]:
jptop50_table.head()

,sync_date,added_at,rank,track_id,album_id
0,2024-06-13 14:21:15+00:00,2024-06-13 09:37:53+00:00,1,78W4mTLIh4qoLu92W4IQhO,40CHqDtwO8xlI3Ns7sZZel
1,2024-06-13 14:21:15+00:00,2024-06-13 09:37:53+00:00,2,0kdqcbwei4MDWFEX5f33yG,6M2PMiBa5zM37GQChwBHA6
2,2024-06-13 14:21:15+00:00,2024-06-13 09:37:53+00:00,3,4dmruTsdHIOjfOIeaFitXK,6lVM8WvZY6lpBO9zrBRnE9
3,2024-06-13 14:21:15+00:00,2024-06-13 09:37:53+00:00,4,00Q3uYmFKFVYTRjbsnUq7H,2Pwsp7jElXMU0fUwzHo1je
4,2024-06-13 14:21:15+00:00,2024-06-13 09:37:53+00:00,5,1aKvZDoLGkNMxoRYgkckZG,6irebIc6UO8fN0jl4UlzBS

In [13]:
jptop50_album_info.head()

,sync_date,album_id,album_name,album_release_date
0,2024-06-13 14:21:15+00:00,40CHqDtwO8xlI3Ns7sZZel,ライラック,2024-04-11
1,2024-06-13 14:21:15+00:00,6M2PMiBa5zM37GQChwBHA6,Bling-Bang-Bang-Born,2024-01-07
2,2024-06-13 14:21:15+00:00,6lVM8WvZY6lpBO9zrBRnE9,幾億光年,2024-01-24
3,2024-06-13 14:21:15+00:00,2Pwsp7jElXMU0fUwzHo1je,I wonder,2024-04-17
4,2024-06-13 14:21:15+00:00,6irebIc6UO8fN0jl4UlzBS,SUPER REAL ME,2024-03-25

In [14]:
jptop50_track_artists_table.head()

                  sync_date                track_id               artist_id
0 2024-06-13 14:21:15+00:00  78W4mTLIh4qoLu92W4IQhO  4QvgGvpgzgyUOo8Yp8LDm9
1 2024-06-13 14:21:15+00:00  0kdqcbwei4MDWFEX5f33yG  0pWR7TsFhvSCnbmHDjWgrE
2 2024-06-13 14:21:15+00:00  4dmruTsdHIOjfOIeaFitXK  63ylN6WBUUxxMsySiDmr0B
3 2024-06-13 14:21:15+00:00  00Q3uYmFKFVYTRjbsnUq7H  71UIOLnsacxQHlU55TvfiH
4 2024-06-13 14:21:15+00:00  1aKvZDoLGkNMxoRYgkckZG  36cgvBn0aadzOijnjjwqMN

#### Following artists

In [72]:
following_atrists_table = get_following_artist()

In [73]:
following_atrists_table

,sync_date,artist_id,artist_name,artist_popularity,artist_followers_total
0,2024-05-26 10:11:06+00:00,4QvgGvpgzgyUOo8Yp8LDm9,Mrs. GREEN APPLE,75,3813586
1,2024-05-26 10:11:06+00:00,5Vo1hnCRmCM6M4thZCInCj,OFFICIAL HIGE DANDISM,67,6477646
2,2024-05-26 10:11:06+00:00,6le80R1opKnTlP4o3KvA2k,Uru,60,923416
3,2024-05-26 10:11:06+00:00,6rs1KAoQnFalSqSU4LTh8g,back number,70,4596759

##### From artist to albums

In [74]:
artist_id = '4QvgGvpgzgyUOo8Yp8LDm9'
atrist_albums_table = artist_get_albums(artist_id)

In [75]:
atrist_albums_table.head()

,sync_date,album_id,album_name,album_release_date
0,2024-05-26 10:11:34+00:00,4tYvszkWNzlqUkiNkOcKT7,Inferno & 更多熱門歌曲,2023-12-01
1,2024-05-26 10:11:34+00:00,3j7aiYai9ezbvxVCgrd2mb,ANTENNA,2023-07-04
2,2024-05-26 10:11:34+00:00,0RFiiRO0L665oWqFlXogNt,5 -Instrumentals-,2020-12-07
3,2024-05-26 10:11:34+00:00,3bRSI9DOQA2KdJ7t6zdW0V,Attitude,2019-10-01
4,2024-05-26 10:11:34+00:00,2zEowQWsCZMuNDJsYTxgRC,ENSEMBLE,2018-04-17

##### From album to tracks
- 只會存artist名單內有指定artist_id的tracks

In [76]:
# by album -> get tracks
album_id = '6q1FkwyDJcYQImWnK6UMCF'
artist_id = '0PYPjvZaOa7bsCq26JOX8d'
album_tracks_table, track_artists_table = album_get_tracks(album_id, artist_id)

In [78]:
album_tracks_table.head()

                  sync_date                track_id                album_id
0 2024-05-26 10:11:59+00:00  7I8kMUSveBJ6WUbc4TcptQ  6q1FkwyDJcYQImWnK6UMCF
1 2024-05-26 10:11:59+00:00  0bxDtb5ZNUd2Eq5xH0t3nf  6q1FkwyDJcYQImWnK6UMCF
2 2024-05-26 10:11:59+00:00  0sDWDasQSnRsndkoEYg4ue  6q1FkwyDJcYQImWnK6UMCF
3 2024-05-26 10:11:59+00:00  7mjamiJ2zplbZQ2ymbn5T7  6q1FkwyDJcYQImWnK6UMCF
4 2024-05-26 10:11:59+00:00  2ayROzS0w3bqU80rpi5E8p  6q1FkwyDJcYQImWnK6UMCF

In [79]:
track_artists_table.head()

                  sync_date                track_id               artist_id
0 2024-05-26 10:11:59+00:00  7I8kMUSveBJ6WUbc4TcptQ  0PYPjvZaOa7bsCq26JOX8d
1 2024-05-26 10:11:59+00:00  0bxDtb5ZNUd2Eq5xH0t3nf  0PYPjvZaOa7bsCq26JOX8d
2 2024-05-26 10:11:59+00:00  0sDWDasQSnRsndkoEYg4ue  0PYPjvZaOa7bsCq26JOX8d
3 2024-05-26 10:11:59+00:00  7mjamiJ2zplbZQ2ymbn5T7  0PYPjvZaOa7bsCq26JOX8d
4 2024-05-26 10:11:59+00:00  2ayROzS0w3bqU80rpi5E8p  0PYPjvZaOa7bsCq26JOX8d

##### My saved tracks

In [41]:
# My saved tracks
mysavedtracks_table, mysavedtracks_album_info, mysavedtracks_track_artists_table = playlist_get_tracks()

In [80]:
mysavedtracks_table.head()

,sync_date,added_at,rank,track_id,album_id
0,2024-05-26 09:04:43+00:00,2024-05-21 00:56:58+00:00,1,0tnhoHUrHfcLi9hPknUFZ4,3bRSI9DOQA2KdJ7t6zdW0V
1,2024-05-26 09:04:43+00:00,2024-05-15 13:49:15+00:00,2,3zbKiko8V3u2yn1RcT8xBZ,1N3qm3w4YsYgXh6XxBjkay
2,2024-05-26 09:04:43+00:00,2024-05-15 13:48:57+00:00,3,3RvdkNMcSy71m0aT6UF9Uf,4Owee1i5rIFJvQczZXSdiQ
3,2024-05-26 09:04:43+00:00,2024-05-15 13:48:03+00:00,4,4dmruTsdHIOjfOIeaFitXK,6lVM8WvZY6lpBO9zrBRnE9
4,2024-05-26 09:04:43+00:00,2024-05-15 13:44:30+00:00,5,5eY7692tmgHB9dbmq6wa2M,4O53dhmIctih3p2suAAgga

In [82]:
mysavedtracks_album_info.head()

,sync_date,album_id,album_name,album_release_date
0,2024-05-26 09:04:43+00:00,3bRSI9DOQA2KdJ7t6zdW0V,Attitude,2019-10-01
1,2024-05-26 09:04:43+00:00,1N3qm3w4YsYgXh6XxBjkay,ROUNDABOUT,2024-01-10
2,2024-05-26 09:04:43+00:00,4Owee1i5rIFJvQczZXSdiQ,ユーモア,2023-01-17
3,2024-05-26 09:04:43+00:00,6lVM8WvZY6lpBO9zrBRnE9,幾億光年,2024-01-24
4,2024-05-26 09:04:43+00:00,4O53dhmIctih3p2suAAgga,晴る,2024-01-05

In [83]:
mysavedtracks_track_artists_table.head()

                  sync_date                track_id               artist_id
0 2024-05-26 09:04:43+00:00  0tnhoHUrHfcLi9hPknUFZ4  4QvgGvpgzgyUOo8Yp8LDm9
1 2024-05-26 09:04:43+00:00  3zbKiko8V3u2yn1RcT8xBZ  7mvhRvEAHiCTQHUnH7fgnv
2 2024-05-26 09:04:43+00:00  3RvdkNMcSy71m0aT6UF9Uf  6rs1KAoQnFalSqSU4LTh8g
3 2024-05-26 09:04:43+00:00  4dmruTsdHIOjfOIeaFitXK  63ylN6WBUUxxMsySiDmr0B
4 2024-05-26 09:04:43+00:00  5eY7692tmgHB9dbmq6wa2M  4UK2Lzi6fBfUi9rpDt6cik

##### Track info

In [60]:
track_id_list = ['0tnhoHUrHfcLi9hPknUFZ4', '3zbKiko8V3u2yn1RcT8xBZ', '3RvdkNMcSy71m0aT6UF9Uf', '7I8kMUSveBJ6WUbc4TcptQ', '2ayROzS0w3bqU80rpi5E8p']
get_track_info(track_list = track_id_list, max_idn = 100)

,sync_date,duration_ms,id,name,popularity
0,2024-06-02 10:21:58+00:00,321306,0tnhoHUrHfcLi9hPknUFZ4,僕のこと,65
1,2024-06-02 10:21:58+00:00,196640,3zbKiko8V3u2yn1RcT8xBZ,青のすみか,71
2,2024-06-02 10:21:58+00:00,288013,3RvdkNMcSy71m0aT6UF9Uf,水平線,71
3,2024-06-02 10:21:58+00:00,252213,7I8kMUSveBJ6WUbc4TcptQ,アイライキュー,33
4,2024-06-02 10:21:58+00:00,227826,2ayROzS0w3bqU80rpi5E8p,Slave of Love,19

#### Workflow

##### DB
1. JP top 50
- jptop50_table: update to DB jptop50_daily directly
- jptop50_album_info: update to DB album_info_update if album_id not exist
- jptop50_track_artists: update to DB new track_id

2. Following artists
- following_atrists_table: update to DB directly

3. atrist_albums_table -> album_tracks_table, track_artists_table 
- atrist_albums_table: loop > total atrist_albums_table > update to DB if album_id not exist
- album_tracks_table: new album > loop > total album_tracks_table > update to DB if track_id not exist
- track_artists_table: new album > loop > total album_tracks_table > update to DB if track_id not exist

4. track get info
- track_info_table: new album > loop > total track_info_table > update to DB if track_id not exist

5. My saved tracks
- mysavedtracks_table: update to DB directly
- mysavedtracks_album_info: update to DB album_info_update if album_id not exist
- mysavedtracks_track_artists_table: update to DB new track_id

6. track get info
- track_info_table: new track > loop > total track_info_table > update to DB if track_id not exist

##### Rule
- 2 需要早於 3
- 3 / 4 要進行就要全都進行, 不能只進行一部分
- 5 / 6 要進行就要全都進行, 不能只進行一部分

In [50]:
# connect to mysql
from mysql import connector
from sqlalchemy import create_engine, Table, MetaData
from sqlalchemy.orm import sessionmaker

In [51]:
# Create a SQLAlchemy engine to connect to the MySQL database
engine = create_engine('mysql+mysqlconnector://dbuser:Vivian_0821@localhost/spotify_project')

##### Work flow 1. JP top 50

In [52]:
playlist_id_jptop50 = '37i9dQZEVXbKXQ4mDTEBXq'
jptop50_table, jptop50_album_info, jptop50_track_artists = playlist_get_tracks(playlist_id_jptop50)

# 建立 Session
Session = sessionmaker(bind = engine)
session = Session()


## jptop50_table: update to DB jptop50_daily directly
jptop50_table_insert = jptop50_table[['sync_date', 'added_at', 'rank', 'track_id', 'album_id']]
jptop50_table_insert.to_sql('jptop50_daily', con = engine, if_exists = 'append', index = False)


## jptop50_album_info: update to DB album_info_update if album_id not exist
jptop50_album_info_insert = jptop50_album_info[['sync_date', 'album_id', 'album_name', 'album_release_date']]
# album_info_update table
metadata = MetaData()
metadata.reflect(bind = engine)
album_info_db = Table('album_info_update', metadata, autoload_with = engine)
# read db table
query_album_info_exist = session.query(album_info_db)
album_info_exist = pd.read_sql(query_album_info_exist.statement, query_album_info_exist.session.bind)
# campare db & new data
merged_album_info = pd.merge(jptop50_album_info_insert, album_info_exist, on = 'album_id', suffixes = ('_new', '_db'), how = 'outer', indicator = True)
# update
to_update = merged_album_info[(merged_album_info['_merge'] == 'both') & (
    (merged_album_info['album_name_new'] != merged_album_info['album_name_db']) |
    (merged_album_info['album_release_date_new'] != merged_album_info['album_release_date_db'])
)]
for _, row in to_update.iterrows():
    session.query(album_info_db).filter_by(album_id = row['album_id']).update({
        'album_name': row['album_name_new'],
        'album_release_date': row['album_release_date_new'],
        'sync_date': row['sync_date_new']
    })
# insert
to_insert = merged_album_info[merged_album_info['_merge'] == 'left_only']
to_insert = to_insert[['sync_date_new', 'album_id', 'album_name_new', 'album_release_date_new']]
to_insert.columns = ['sync_date', 'album_id', 'album_name', 'album_release_date']
to_insert.to_sql('album_info_update', con = engine, if_exists = 'append', index = False)


## jptop50_track_artists: update to DB if new track_id
jptop50_track_artists_insert = jptop50_track_artists[['sync_date', 'track_id', 'artist_id']]
# track_artists_update table
metadata = MetaData()
metadata.reflect(bind = engine)
track_artists_db = Table('track_artists_update', metadata, autoload_with = engine)
# read db table
query_track_artists_exist = session.query(track_artists_db)
track_artists_exist = pd.read_sql(query_track_artists_exist.statement, query_track_artists_exist.session.bind)

# insert
to_insert = jptop50_track_artists_insert[[track not in list(track_artists_exist['track_id'].unique()) for track in jptop50_track_artists_insert['track_id']]]
to_insert.to_sql('track_artists_update', con = engine, if_exists = 'append', index = False)


# 提交更新
session.commit()

# 關閉 Session
session.close()

##### GLOBAL

In [53]:
playlist_id_glbtop50 = '37i9dQZEVXbNG2KDcFcKOF'
glbtop50_table, glbtop50_album_info, glbtop50_track_artists = playlist_get_tracks(playlist_id_glbtop50)

# 建立 Session
Session = sessionmaker(bind = engine)
session = Session()


## glbtop50_table: update to DB glbtop50_daily directly
glbtop50_table_insert = glbtop50_table[['sync_date', 'added_at', 'rank', 'track_id', 'album_id']]
glbtop50_table_insert.to_sql('glbtop50_daily', con = engine, if_exists = 'append', index = False)


## glbtop50_album_info: update to DB album_info_update if album_id not exist
glbtop50_album_info_insert = glbtop50_album_info[['sync_date', 'album_id', 'album_name', 'album_release_date']]
# album_info_update table
metadata = MetaData()
metadata.reflect(bind = engine)
album_info_db = Table('album_info_update', metadata, autoload_with = engine)
# read db table
query_album_info_exist = session.query(album_info_db)
album_info_exist = pd.read_sql(query_album_info_exist.statement, query_album_info_exist.session.bind)
# campare db & new data
merged_album_info = pd.merge(glbtop50_album_info_insert, album_info_exist, on = 'album_id', suffixes = ('_new', '_db'), how = 'outer', indicator = True)
# update
to_update = merged_album_info[(merged_album_info['_merge'] == 'both') & (
    (merged_album_info['album_name_new'] != merged_album_info['album_name_db']) |
    (merged_album_info['album_release_date_new'] != merged_album_info['album_release_date_db'])
)]
for _, row in to_update.iterrows():
    session.query(album_info_db).filter_by(album_id = row['album_id']).update({
        'album_name': row['album_name_new'],
        'album_release_date': row['album_release_date_new'],
        'sync_date': row['sync_date_new']
    })
# insert
to_insert = merged_album_info[merged_album_info['_merge'] == 'left_only']
to_insert = to_insert[['sync_date_new', 'album_id', 'album_name_new', 'album_release_date_new']]
to_insert.columns = ['sync_date', 'album_id', 'album_name', 'album_release_date']
to_insert.to_sql('album_info_update', con = engine, if_exists = 'append', index = False)


## glbtop50_track_artists: update to DB if new track_id
glbtop50_track_artists_insert = glbtop50_track_artists[['sync_date', 'track_id', 'artist_id']]
# track_artists_update table
metadata = MetaData()
metadata.reflect(bind = engine)
track_artists_db = Table('track_artists_update', metadata, autoload_with = engine)
# read db table
query_track_artists_exist = session.query(track_artists_db)
track_artists_exist = pd.read_sql(query_track_artists_exist.statement, query_track_artists_exist.session.bind)

# insert
to_insert = glbtop50_track_artists_insert[[track not in list(track_artists_exist['track_id'].unique()) for track in glbtop50_track_artists_insert['track_id']]]
to_insert.to_sql('track_artists_update', con = engine, if_exists = 'append', index = False)


# 提交更新
session.commit()

# 關閉 Session
session.close()

##### Work flow 2. Following artists

In [54]:
following_atrists_table = get_following_artist()

# 建立 Session
Session = sessionmaker(bind = engine)
session = Session()

following_atrists_table.to_sql('following_atrists_daily', con = engine, if_exists = 'append', index = False)

# 提交更新
session.commit()

# 關閉 Session
session.close()

##### Work flow 3 & 4 先pass

##### Work flow 5. My saved tracks

In [55]:
mysave_table, mysave_album_info, mysave_track_artists = playlist_get_tracks()

# 建立 Session
Session = sessionmaker(bind = engine)
session = Session()


## mysave_table: update to DB mysave_daily directly
mysave_table_insert = mysave_table[['sync_date', 'added_at', 'rank', 'track_id', 'album_id']]
mysave_table_insert.to_sql('mysave_daily', con = engine, if_exists = 'append', index = False)


## mysave_album_info: update to DB album_info_update if album_id not exist
mysave_album_info_insert = mysave_album_info[['sync_date', 'album_id', 'album_name', 'album_release_date']]
# album_info_update table
metadata = MetaData()
metadata.reflect(bind = engine)
album_info_db = Table('album_info_update', metadata, autoload_with = engine)
# read db table
query_album_info_exist = session.query(album_info_db)
album_info_exist = pd.read_sql(query_album_info_exist.statement, query_album_info_exist.session.bind)
# campare db & new data
merged_album_info = pd.merge(mysave_album_info_insert, album_info_exist, on = 'album_id', suffixes = ('_new', '_db'), how = 'outer', indicator = True)
# update
to_update = merged_album_info[(merged_album_info['_merge'] == 'both') & (
    (merged_album_info['album_name_new'] != merged_album_info['album_name_db']) |
    (merged_album_info['album_release_date_new'] != merged_album_info['album_release_date_db'])
)]
for _, row in to_update.iterrows():
    session.query(album_info_db).filter_by(album_id = row['album_id']).update({
        'album_name': row['album_name_new'],
        'album_release_date': row['album_release_date_new'],
        'sync_date': row['sync_date_new']
    })
# insert
to_insert = merged_album_info[merged_album_info['_merge'] == 'left_only']
to_insert = to_insert[['sync_date_new', 'album_id', 'album_name_new', 'album_release_date_new']].drop_duplicates()
to_insert.columns = ['sync_date', 'album_id', 'album_name', 'album_release_date']
to_insert.to_sql('album_info_update', con = engine, if_exists = 'append', index = False)


## mysave_track_artists: update to DB if new track_id
mysave_track_artists_insert = mysave_track_artists[['sync_date', 'track_id', 'artist_id']]
# track_artists_update table
metadata = MetaData()
metadata.reflect(bind = engine)
track_artists_db = Table('track_artists_update', metadata, autoload_with = engine)
# read db table
query_track_artists_exist = session.query(track_artists_db)
track_artists_exist = pd.read_sql(query_track_artists_exist.statement, query_track_artists_exist.session.bind)

# insert
to_insert = mysave_track_artists_insert[[track not in list(track_artists_exist['track_id'].unique()) for track in mysave_track_artists_insert['track_id']]]
to_insert.to_sql('track_artists_update', con = engine, if_exists = 'append', index = False)


# 提交更新
session.commit()

# 關閉 Session
session.close()

### My recent played

In [56]:
my_recently_table, my_recently_album_info, my_recently_track_artists = my_recently_played()

# 建立 Session
Session = sessionmaker(bind = engine)
session = Session()

## my_recently_table: update to DB my_recently_played if data not exist
my_recently_table_insert = my_recently_table[['sync_date', 'played_at', 'rank', 'track_id', 'album_id']]

# my_recently_played table
metadata = MetaData()
metadata.reflect(bind = engine)
my_recently_played_db = Table('my_recently_played', metadata, autoload_with = engine)
# read db table
query_my_recently_played_exist = session.query(my_recently_played_db)
my_recently_played_exist = pd.read_sql(query_my_recently_played_exist.statement, query_my_recently_played_exist.session.bind)
# campare db & new data
my_recently_played_exist['played_at'] = my_recently_played_exist['played_at'].dt.floor('S').dt.tz_localize('UTC') # set data from DB as UTC timezone
my_recently_table_insert['played_at'] = my_recently_table_insert['played_at'].dt.floor('S')
# insert
to_insert = my_recently_table_insert[my_recently_table_insert['played_at'] > max(my_recently_played_exist['played_at'])]
to_insert.to_sql('my_recently_played', con = engine, if_exists = 'append', index = False)


## my_recently_album_info: update to DB album_info_update if album_id not exist
my_recently_album_info_insert = my_recently_album_info[['sync_date', 'album_id', 'album_name', 'album_release_date']]
# album_info_update table
metadata = MetaData()
metadata.reflect(bind = engine)
album_info_db = Table('album_info_update', metadata, autoload_with = engine)
# read db table
query_album_info_exist = session.query(album_info_db)
album_info_exist = pd.read_sql(query_album_info_exist.statement, query_album_info_exist.session.bind)
# campare db & new data
merged_album_info = pd.merge(my_recently_album_info_insert, album_info_exist, on = 'album_id', suffixes = ('_new', '_db'), how = 'outer', indicator = True)
# update
to_update = merged_album_info[(merged_album_info['_merge'] == 'both') & (
    (merged_album_info['album_name_new'] != merged_album_info['album_name_db']) |
    (merged_album_info['album_release_date_new'] != merged_album_info['album_release_date_db'])
)]
for _, row in to_update.iterrows():
    session.query(album_info_db).filter_by(album_id = row['album_id']).update({
        'album_name': row['album_name_new'],
        'album_release_date': row['album_release_date_new'],
        'sync_date': row['sync_date_new']
    })
# insert
to_insert = merged_album_info[merged_album_info['_merge'] == 'left_only']
to_insert = to_insert[['sync_date_new', 'album_id', 'album_name_new', 'album_release_date_new']]
to_insert.columns = ['sync_date', 'album_id', 'album_name', 'album_release_date']
to_insert.to_sql('album_info_update', con = engine, if_exists = 'append', index = False)


## my_recently_track_artists: update to DB if new track_id
my_recently_track_artists_insert = my_recently_track_artists[['sync_date', 'track_id', 'artist_id']]
# track_artists_update table
metadata = MetaData()
metadata.reflect(bind = engine)
track_artists_db = Table('track_artists_update', metadata, autoload_with = engine)
# read db table
query_track_artists_exist = session.query(track_artists_db)
track_artists_exist = pd.read_sql(query_track_artists_exist.statement, query_track_artists_exist.session.bind)

# insert
to_insert = my_recently_track_artists_insert[[track not in list(track_artists_exist['track_id'].unique()) for track in my_recently_track_artists_insert['track_id']]]
to_insert.to_sql('track_artists_update', con = engine, if_exists = 'append', index = False)


# 提交更新
session.commit()

# 關閉 Session
session.close()

### Track info

In [57]:
# 建立 Session
Session = sessionmaker(bind = engine)
session = Session()


# current mysave_daily table in DB
metadata = MetaData()
metadata.reflect(bind = engine)
mysave_daily = Table('mysave_daily', metadata, autoload_with = engine)
# read db table
mysave_daily_exist = pd.read_sql(session.query(mysave_daily).statement, session.query(mysave_daily).session.bind)

# current mysave_daily table in DB
metadata = MetaData()
metadata.reflect(bind = engine)
jptop50_daily = Table('jptop50_daily', metadata, autoload_with = engine)
# read db table
jptop50_daily_exist = pd.read_sql(session.query(jptop50_daily).statement, session.query(jptop50_daily).session.bind)

# current mysave_daily table in DB
metadata = MetaData()
metadata.reflect(bind = engine)
glbtop50_daily = Table('glbtop50_daily', metadata, autoload_with = engine)
# read db table
glbtop50_daily_exist = pd.read_sql(session.query(glbtop50_daily).statement, session.query(glbtop50_daily).session.bind)

# current my_recently_played table in DB
metadata = MetaData()
metadata.reflect(bind = engine)
my_recently_played = Table('my_recently_played', metadata, autoload_with = engine)
# read db table
my_recently_played_exist = pd.read_sql(session.query(my_recently_played).statement, session.query(my_recently_played).session.bind)

# current track_info_update in DB
metadata = MetaData()
metadata.reflect(bind = engine)
track_info_db = Table('track_info_update', metadata, autoload_with = engine)
# read db table
query_track_info_exist = session.query(track_info_db)
track_info_exist = pd.read_sql(query_track_info_exist.statement, query_track_info_exist.session.bind)

# ---------------------------------------------------------------------------------------------------------------- #

# filter the track not in track_info_update table
update_track_list = []
for track in list(mysave_daily_exist['track_id']) + list(jptop50_daily_exist['track_id']) + list(my_recently_played_exist['track_id']) + list(glbtop50_daily_exist['track_id']):
    if track not in track_info_exist['track_id']:
        update_track_list.append(track)
unique_update_track_list = list(set(update_track_list))

# insert 
to_insert = get_track_info(unique_update_track_list, max_idn = 50)
to_insert.columns = ['sync_date', 'track_duration_ms', 'track_id', 'track_name', 'track_popularity']
to_insert.to_sql('track_info_update', con = engine, if_exists = 'append', index = False)


# 提交更新
session.commit()

# 關閉 Session
session.close()

### Track Feature

In [58]:
# 建立 Session
Session = sessionmaker(bind = engine)
session = Session()


# current mysave_daily table in DB
metadata = MetaData()
metadata.reflect(bind = engine)
mysave_daily = Table('mysave_daily', metadata, autoload_with = engine)
# read db table
mysave_daily_exist = pd.read_sql(session.query(mysave_daily).statement, session.query(mysave_daily).session.bind)

# current mysave_daily table in DB
metadata = MetaData()
metadata.reflect(bind = engine)
jptop50_daily = Table('jptop50_daily', metadata, autoload_with = engine)
# read db table
jptop50_daily_exist = pd.read_sql(session.query(jptop50_daily).statement, session.query(jptop50_daily).session.bind)

# current mysave_daily table in DB
metadata = MetaData()
metadata.reflect(bind = engine)
glbtop50_daily = Table('glbtop50_daily', metadata, autoload_with = engine)
# read db table
glbtop50_daily_exist = pd.read_sql(session.query(glbtop50_daily).statement, session.query(glbtop50_daily).session.bind)

# current my_recently_played table in DB
metadata = MetaData()
metadata.reflect(bind = engine)
my_recently_played = Table('my_recently_played', metadata, autoload_with = engine)
# read db table
my_recently_played_exist = pd.read_sql(session.query(my_recently_played).statement, session.query(my_recently_played).session.bind)

# current track_feature_update in DB
metadata = MetaData()
metadata.reflect(bind = engine)
track_feature_db = Table('track_feature_update', metadata, autoload_with = engine)
# read db table
query_track_feature_exist = session.query(track_feature_db)
track_feature_exist = pd.read_sql(query_track_feature_exist.statement, query_track_feature_exist.session.bind)

# ---------------------------------------------------------------------------------------------------------------- #

# filter the track not in track_feature_update table
update_track_list = []
for track in list(mysave_daily_exist['track_id']) + list(jptop50_daily_exist['track_id']) + list(my_recently_played_exist['track_id']) + list(glbtop50_daily_exist['track_id']):
    if track not in track_feature_exist['track_id']:
        update_track_list.append(track)
unique_update_track_list = list(set(update_track_list))

# insert 
to_insert = get_track_feature(unique_update_track_list, max_idn = 50)
to_insert.columns = [
    'sync_date', 'track_id', 'track_danceability', 'track_energy', 'track_key', 'track_loudness', 
    'track_mode', 'track_speechiness', 'track_acousticness', 'track_instrumentalness', 'track_liveness',
    'track_valence', 'track_tempo', 'track_type', 'track_time_signature'
    ]
to_insert.to_sql('track_feature_update', con = engine, if_exists = 'append', index = False)


# 提交更新
session.commit()

# 關閉 Session
session.close()

In [ ]:
# add new song to db

In [ ]:
# in JP Top 50 or not